---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: not-used
spec:
  interval: 30m
  values:
    credentials:
      cf-restic:
        type: s3
        url: "${CF_S3_RESTIC_URL:-https://s3.example.com}"
        accessKey: "${CF_S3_RESTIC_ID:-restic}"
        secretKey: "${CF_S3_RESTIC_KEY:-changeme}"
        encrKey: "${CF_S3_RESTIC_KEY:-changeme}"

      rfs-restic:
        type: s3
        url: "${RUSTFS_S3_RESTIC_URL:-https://s3.example.com}"
        accessKey: "${RUSTFS_S3_RESTIC_ID:-restic}"
        secretKey: "${RUSTFS_S3_RESTIC_KEY:-changeme}"
        encrKey: "${RUSTFS_S3_RESTIC_KEY:-changeme}"