name: doco-cd
reference: main
working_dir: ./docker/nas/.doco-cd
compose_files:
  - compose.yaml
force_recreate: true
---
name: nas
working_dir: ./docker/nas/apps
auto_discovery:
  enabled: true
  depth: 0
  delete: true
force_recreate: true
reconciliation:
  enabled: true
  interval: 3600
env_files:
  - ../../base.enc.env
external_secrets:
  CF_TUNNEL_TOKEN_NAS: dffe6371-4a92-4c17-a85a-b4d40027d83a
  DOCKHAND_HAWSER_TOKEN_NAS: 8a808d6d-2444-430a-832f-b4d400540184
  RUSTFS_ACCESS_KEY: 82d19e1c-4c3f-4101-a0ff-b4d40056dd0a
  RUSTFS_SECRET_KEY: 213abdd2-c87e-4c74-9614-b4d40057095e
  ADGUARD_PASSWORD: 921ffc13-9f1a-4c2f-828e-b4da001e63ab
  ADGUARD_USERNAME: 976499c7-5b7d-4f89-a67b-b4da001e3f63
  ADGUARD_URL: ac55554b-81dc-412d-b1b5-b4da001e2845