name: Nas
working_dir: ./docker/nas/apps
auto_discovery:
  enabled: true
  depth: 0
  delete: true
env_files:
  - ../../secrets.enc.env
  - ../../base.enc.env
force_recreate: false
reconciliation:
  enabled: true
  interval: 3600
