---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - opnsense.yaml
  - speedtest.yaml
  - nas-node.yaml
  - nas-docker.yaml
  - seb-node.yaml
  - seb-docker.yaml
  - seb-doco-cd.yaml
