---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: docker-nas
  namespace: kube-prometheus-stack
spec:
  staticConfigs:
    - targets:
        - ${SCALE_IP}:9323 # metrics.docker.nas.local
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: instance
      replacement: docker-nas
    - action: replace
      targetLabel: job
      replacement: docker-nas