
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: docker-seb
  namespace: kube-prometheus-stack
spec:
  staticConfigs:
    - targets:
        - metrics.docker.seb.local
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: instance
      replacement: docker-seb
    - action: replace
      targetLabel: job
      replacement: docker-seb
