---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grocy
  namespace: grocy
spec:
  interval: 30m
  timeout: 25m
  maxHistory: 3
  # enabled | warn
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: grocy
      version: 22.11.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gatus:
      group: assets
    global:
      stopAll: false
    credentials:
      cf-restic:
        bucket: "${CF_S3_RESTIC_BUCKET}-grocy"
      rfs-restic:
        bucket: "${RUSTFS_S3_RESTIC_BUCKET}-grocy"
    image:
      repository: ghcr.io/trueforge-org/grocy
      tag: 4.7.1@sha256:2815f994b7c350c0f80cef0895da12c730308b07dff6a595192d0afa56bf1ba4
      pullPolicy: IfNotPresent

    workload:
      main:
        podSpec:
          containers:
            main:
              probes:
                liveness:
                  #path: "/api/system/info"
                  type: tcp
                readiness:
                  type: tcp
                  #path: "/api/system/info"
                startup:
                  type: tcp
              env:
                GROCY_AUTH_CLASS: 'Grocy\Middleware\Auth\ReverseProxyAuthMiddleware'
                GROCY_REVERSE_PROXY_AUTH_HEADER: "Remote-User"
                GROCY_REVERSE_PROXY_AUTH_USE_ENV: false
                GROCY_DISABLE_AUTH: false

    ingress:
      main:
        enabled: true
        ingressClassName: "external"
        hosts:
          - host: grocy.${DOMAIN_2}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: true
            auth:
              type: "authelia"
              internalHost: "authelia.authelia.svc.cluster.local:9091"
              externalHost: "auth.${DOMAIN_2}"
          certManager:
            enabled: true
            certificateIssuer: general-le-prod

    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
