x-healthcheck: &healthcheck
  test: ["CMD", "/doco-cd", "healthcheck"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  doco-cd:
    image: ghcr.io/kimdre/doco-cd:0.122@sha256:16e2db9a98d622711e7fc5c559186d0e020f6cbd08cf23b171b032b35d4e8c4b
    container_name: doco-cd
    restart: unless-stopped
    networks:
      - internal
      - network_internal
    ports:
      - "9080:9080"
      - "9120:9120"
    healthcheck: *healthcheck
    environment:
      TZ: America/New_York
      HTTP_PORT: 9080
      APPRISE_API_URL: http://apprise:8000/notify
      APPRISE_NOTIFY_URLS: http://apprise:8000/notify/doco-cd
      APPRISE_NOTIFY_LEVEL: success
      DOCKER_SWARM_FEATURES: "false"
      DEPLOY_CONFIG_BASE_DIR: ./docker/seb
      PASS_ENV: "false"
      POLL_CONFIG: |
        - url: https://github.com/xstar97/home-ops
          reference: main
          interval: 3600
      SSH_PRIVATE_KEY_PASSPHRASE: ""
      SSH_PRIVATE_KEY_FILE: /run/secrets/ssh_private_key
      SOPS_AGE_KEY_FILE: /run/secrets/sops_age_key
      WEBHOOK_SECRET_FILE: /run/secrets/webhook_secret
      # GIT_ACCESS_TOKEN_FILE: /run/secrets/git_access_token
      GITHUB_APP_ID_FILE: /run/secrets/github_app_id
      GITHUB_APP_PRIVATE_KEY_FILE: /run/secrets/github_app_private_key
      SECRET_PROVIDER_ACCESS_TOKEN_FILE: /run/secrets/secret_provider_access_token
      SECRET_PROVIDER: bitwarden_sm
      SELF_UPDATE_ENABLED: "true"
      SELF_UPDATE_STRATEGY: applier
    secrets:
      - ssh_private_key
      - sops_age_key
      - webhook_secret
      # - git_access_token
      - github_app_id
      - github_app_private_key
      - secret_provider_access_token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - doco_data:/data
networks:
  internal:
    driver: bridge
  network_internal:
    external: true
volumes:
  doco_data: {}
secrets:
  ssh_private_key:
    file: ${SSH_KEY_FILE}
  sops_age_key:
    file: ${AGEKEY_FILE}
  webhook_secret:
    file: ${WEBHOOK_FILE}
  # git_access_token:
  #   file: ${GAT_FILE}
  github_app_id:
    file: ${GITHUB_APP_ID_FILE}
  github_app_private_key:
    file: ${GITHUB_APP_PRIVATE_KEY_FILE}
  secret_provider_access_token:
    file: ${BITWARDEN_SM_FILE}
