services:
  apprise:
    image: caronc/apprise:v1.5.1@sha256:1871ed736799f6320d5061b72a60507f62c8747026e830175dc4b9f8adbf78dd
    container_name: apprise
    restart: unless-stopped
    networks:
      - internal
    expose:
      - "8000"
    environment:
      TZ: America/New_York
      APPRISE_WORKER_COUNT: 1
      APPRISE_STATEFUL_MODE: simple
      # APPRISE_ADMIN: "y"
    volumes:
      - ${DOCKER_DATA_DIR}/apprise/config:/config
      - ${DOCKER_DATA_DIR}/apprise/attach:/attach
    healthcheck:
      test: ["CMD-SHELL", "curl -fs -o /dev/null http://localhost:8000/status"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    labels:
      - wud.tag.include=^\\d+\\.\\d+\\.\\d+$
  doco-cd:
    image: ghcr.io/kimdre/doco-cd:0.110@sha256:69dd02c0ff847870d29d4fc769d309913826f73a2fbd18254f4ccb4d04e216e1
    container_name: doco-cd
    restart: unless-stopped
    depends_on:
      apprise:
        condition: service_healthy
    networks:
      - internal
      - network_internal
    ports:
      - "9080:9080"
      - "9120:9120"
    environment:
      TZ: America/New_York
      HTTP_PORT: 9080
      APPRISE_API_URL: http://apprise:8000/notify
      APPRISE_NOTIFY_URLS: http://apprise:8000/notify/doco-cd
      APPRISE_NOTIFY_LEVEL: success
      DOCKER_SWARM_FEATURES: "false"
      DEPLOY_CONFIG_BASE_DIR: ./docker/seb
      PASS_ENV: "false"
      POLL_CONFIG: |
        - url: https://github.com/xstar97/home-ops
          reference: main
          interval: 3600
      SSH_PRIVATE_KEY_PASSPHRASE: ""
      SSH_PRIVATE_KEY_FILE: /run/secrets/ssh_private_key
      SOPS_AGE_KEY_FILE: /run/secrets/sops_age_key
      WEBHOOK_SECRET_FILE: /run/secrets/webhook_secret
      GIT_ACCESS_TOKEN_FILE: /run/secrets/git_access_token
    secrets:
      - ssh_private_key
      - sops_age_key
      - webhook_secret
      - git_access_token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - doco_data:/data
    healthcheck:
      test: ["CMD", "/doco-cd", "healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    labels:
      - wud.tag.include=^\\d+\\.\\d+\\.\\d+$
networks:
  internal:
    driver: bridge
  network_internal:
    external: true
volumes:
  doco_data: {}
secrets:
  ssh_private_key:
    file: ${SSH_KEY_FILE}
  sops_age_key:
    file: ${AGEKEY_FILE}
  webhook_secret:
    file: ${WEBHOOK_FILE}
  git_access_token:
    file: ${GAT_FILE}
