services:
  apprise:
    image: caronc/apprise:v1.5.0@sha256:43673bf62faa88148298d52664b37b4860189555db0b251b54d79a3ef3a173cf
    container_name: apprise
    restart: unless-stopped
    networks:
      - internal
    expose:
      - "8000"
    environment:
      TZ: America/New_York
      APPRISE_WORKER_COUNT: 1
      APPRISE_STATEFUL_MODE: simple
      # APPRISE_ADMIN: "y"
    volumes:
      - ${DOCKER_DATA_DIR}/apprise/config:/config
      - ${DOCKER_DATA_DIR}/apprise/attach:/attach
    healthcheck:
      test: ["CMD-SHELL", "curl -fs -o /dev/null http://localhost:8000/status"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    labels:
      - wud.tag.include=^\\d+\\.\\d+\\.\\d+$
  doco-cd:
    image: ghcr.io/kimdre/doco-cd:0.91@sha256:dfe53c9c5a673b17582683798ccda0f955e81a7f995d09b7cc2ff452dfd4ede1
    container_name: doco-cd
    restart: unless-stopped
    depends_on:
      apprise:
        condition: service_healthy
    networks:
      - internal
      - network_internal
    ports:
      - "9080:9080"
      - "9120:9120"
    environment:
      TZ: America/New_York
      HTTP_PORT: 9080
      SSH_PRIVATE_KEY_FILE: /run/secrets/ssh_private_key
      SSH_PRIVATE_KEY_PASSPHRASE: ""
      SOPS_AGE_KEY_FILE: /run/secrets/sops_age_key
      APPRISE_API_URL: http://apprise:8000/notify
      APPRISE_NOTIFY_URLS: http://apprise:8000/notify/doco-cd
      APPRISE_NOTIFY_LEVEL: success
      DOCKER_SWARM_FEATURES: "false"
      DEPLOY_CONFIG_BASE_DIR: ./docker/seb/
      WEBHOOK_SECRET_FILE: /run/secrets/webhook_secret
      PASS_ENV: "false"
      POLL_CONFIG: |
        - url: https://github.com/xstar97/home-ops
          reference: main
          interval: 3600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - doco_data:/data
      - ${SSH_KEY_FILE}:/run/secrets/ssh_private_key:ro
      - ${AGEKEY_FILE}:/run/secrets/sops_age_key:ro
      - ${WEBHOOK_FILE}:/run/secrets/webhook_secret:ro
    healthcheck:
      test: ["CMD", "/doco-cd", "healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    labels:
      - wud.tag.include=^\\d+\\.\\d+\\.\\d+$
networks:
  internal:
    driver: bridge
  network_internal:
    external: true
volumes:
  doco_data: {}