# Preserve the existing Talos API certificate SANs.
machine:
  certSANs:
    - 127.0.0.1
    - ${VIP}
---
apiVersion: v1alpha1
kind: KubeNetworkConfig
podSubnets:
  - ${PODNET}
serviceSubnets:
  - ${SVCNET}
