apiVersion: v1alpha1
kind: ResolverConfig
nameservers:
  - address: 10.0.0.1
  - address: 1.1.1.1
  - address: 8.8.8.8
hostDNS:
  enabled: true
  forwardKubeDNSToHost: true
  resolveMemberNames: true
searchDomains:
  disableDefault: true
