---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
  - name: kromgo-config-file2
    files:
      - config.yaml=./config.yaml
    options:
      labels:
        github.com/xstar97/home-ops/kromgo: "config.yaml"
generatorOptions:
  disableNameSuffixHash: true