apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kromgo
  namespace: kromgo
spec:
  interval: 30m
  timeout: 25m
  maxHistory: 3
  # enabled | warn
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: kromgo
      version: 3.1.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    gatus:
      group: observability
    configsImage:
      repository: ghcr.io/home-operations/k8s-sidecar
      pullPolicy: IfNotPresent
      tag: 2.8.0@sha256:d5ff60ed4eaff14686353ced6e6988e368e5556c8768addb245b304b9edf7233

    workload:
      main:
        podSpec:
          containers:
            configs:
              enabled: true
              imageSelector: configsImage
              probes:
                liveness:
                  enabled: true
                  port: "{{ .Values.service.main.ports.main.port }}"
                readiness:
                  enabled: true
                  port: "{{ .Values.service.main.ports.main.port }}"
                startup:
                  enabled: true
                  port: "{{ .Values.service.main.ports.main.port }}"
              env:
                FOLDER: "{{ .Values.persistence.config.mountPath }}"
                LABEL: kromgo.greenehomelab.com/enabled
                NAMESPACE: kromgo
                RESOURCE: configmap
                UNIQUE_FILENAMES: false
                METHOD: WATCH
                HEALTH_PORT: "9999"
    ingress:
      main:
        enabled: true
        ingressClassName: "external"
        hosts:
          - host: kromgo.${DOMAIN_2}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: general-le-prod

    persistence:
      configfile:
        enabled: false
      config:
        enabled: true
        mountPath: /config
        targetSelectAll: true

    # -- Whether Role Based Access Control objects like roles and rolebindings should be created
    rbac:
      main:
        enabled: true
        primary: true
        clusterWide: true
        rules:
          - apiGroups:
              - "networking.k8s.io"
            resources:
              - "ingresses"
            verbs:
              - "get"
              - "list"
              - "watch"
          - apiGroups: [""]
            resources:
              - "configmaps"
              - "secrets"
              - "services"
            verbs:
              - "get"
              - "list"
              - "watch"
          - apiGroups:
              - "gateway.networking.k8s.io"
            resources:
              - "httproutes"
            verbs:
              - "get"
              - "list"
              - "watch"
    # -- The service account the pods will use to interact with the Kubernetes API
    serviceAccount:
      main:
        enabled: true
        primary: true
    podOptions:
      automountServiceAccountToken: true
