apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kromgo
namePrefix: ""
nameSuffix: ""
resources:
  - helm-release.yaml
  - namespace.yaml
configMapGenerator:
  - name: kromgo-config-file
    namespace: kromgo
    files:
      - ./config.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
components:
  - ../../../../components/notifications/discord
