---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-manifests
  namespace: flux-system
spec:
  interval: 2h
  url: oci://ghcr.io/fluxcd/flux-manifests
  ref:
    tag: v2.9.5
    digest: sha256:321bf281b6cc6529506d97c37f478b78445e110f1f8ca5111320d14ca369d1dd
