---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: renovate-operator
  namespace: flux-system
spec:
  interval: 6h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://ghcr.io/mogenius/helm-charts/renovate-operator
  ref:
    tag: 6.3.0@sha256:f82d88812ad9d40fb6d9390f80cf8898c9f0eef5a4cceaed4b862fb649676f53
