---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metube
  namespace: metube
spec:
  interval: 30m
  chart:
    spec:
      chart: metube
      version: 18.6.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 30m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gatus:
      group: media-downloaders
    global:
      stopAll: false
    credentials:
      cf-restic:
        type: s3
        url: "${CF_S3_RESTIC_URL}"
        bucket: "${CF_S3_RESTIC_BUCKET}-metube"
        accessKey: "${CF_S3_RESTIC_ID}"
        secretKey: "${CF_S3_RESTIC_KEY}"
        encrKey: "${CF_S3_RESTIC_KEY}"
    securityContext:
      readOnlyRootFilesystem: false
    service:
      main:
        type: ClusterIP
        ports:
          main:
            port: 8081
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                STATE_DIR: "{{.Values.persistence.config.mountPath }}"
                DOWNLOAD_DIR: "{{.Values.persistence.downloads.mountPath }}"
                OUTPUT_TEMPLATE: "%(title)s.%(ext)s"
                YTDL_OPTIONS: "{}"
    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        hosts:
          - host: metube.${DOMAIN_2}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: true
            auth:
              type: "authelia"
              internalHost: "authelia.authelia.svc.cluster.local:9091"
              externalHost: "auth.${DOMAIN_2}"
          certManager:
            enabled: true
            certificateIssuer: general-le-prod
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      downloads:
        enabled: true
        type: nfs
        server: ${SCALE_IP}
        path: ${DOWNLOADS_NFS}/complete/metube
        mountPath: "${DOWNLOADS_LOCAL}"
