---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: prowlarr
spec:
  interval: 30m
  timeout: 25m
  maxHistory: 3
  # enabled | warn
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: prowlarr
      version: 22.11.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gatus:
      group: media-indexers
    global:
      stopAll: false
    credentials:
      cf-restic:
        bucket: "${CF_S3_RESTIC_BUCKET}-prowlarr"
      rfs-restic:
        bucket: "${RUSTFS_S3_RESTIC_BUCKET}-prowlarr"
    securityContext:
      readOnlyRootFilesystem: false
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                # PROWLARR__SERVER__PORT: "{{ .Values.service.main.ports.main.port }}"
                PROWLARR__AUTH__METHOD: External
                PROWLARR__AUTH__REQUIRED: DisabledForLocalAddresses
                PROWLARR__APP__THEME: dark
    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        hosts:
          - host: prowlarr.${DOMAIN_2}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: true
          homepage:
            enabled: true
            group: "Media Indexer"
            widget:
              custom:
                key: "${PROWLARR_KEY}"
          certManager:
            enabled: true
            certificateIssuer: general-le-prod
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
