apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: truenas-exporter
  namespace: truenas-exporter
spec:
  interval: 30m
  timeout: 25m
  maxHistory: 3
  driftDetection:
    mode: warn
  chart:
    spec:
      chart: truenas-exporter
      version: 5.3.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gatus:
      group: observability
    global:
      stopAll: false
    image:
      repository: ghcr.io/supporterino/truenas-graphite-to-prometheus
      tag: v2.2.1@sha256:60e7645f74a3243d7fb9e6a15c05ea3b4cddfd2bc7ba9e2b11321ce1d38286dd
      pullPolicy: IfNotPresent

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${TRUENAS_EXPORTER_IP}
        integrations:
          metallb:
            enabled: true

    resources:
      requests:
        cpu: 10m
    
    configmap:
      dashboard:
        enabled: false
