apiVersion: v1alpha1
kind: LinkConfig
name: ens3
up: true
addresses:
  - address: ${CONTROL1IP}/24
routes:
  - gateway: ${GATEWAY}
---
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: ${VIP}
link: ens3