area/github:
  - changed-files:
      - any-glob-to-any-file: .github/**/*
area/kubernetes:
  - changed-files:
      - any-glob-to-any-file: clusters/**/*
area/docker:
  - changed-files:
      - any-glob-to-any-file: docker/**/*
