---
# Area
- { name: "area/github",                 color: "ee01e4" }
- { name: "area/cluster",                color: "ee01e4" }
- { name: "area/docker",                color: "ee01e4" }
- { name: "area/taskfile",               color: "ee01e4" }
# Renovate
- { name: "renovate/container",          color: "027fa0" }
- { name: "renovate/github-action",      color: "027fa0" }
- { name: "renovate/github-release",     color: "027fa0" }
- { name: "renovate/helm",               color: "027fa0" }
- { name: "renovate/kubernetes-api",     color: "#a2eeef"}
- { name: "renovate/grafana-dashboard",  color: "#a2eeef"}
# Semantic Type
- { name: "type/pin",                    color: "ffec19" }
- { name: "type/digest",                 color: "ffec19" }
- { name: "type/patch",                  color: "ffec19" }
- { name: "type/minor",                  color: "ff9800" }
- { name: "type/major",                  color: "f6412d" }
- { name: "type/break",                  color: "f6412d" }
- { name: "type/manual",                  color: "f6412d" }
# Uncategorized
- { name: "hold/upstream",               color: "ee0701" }
- { name: "automerge",                   color: "0e8a16" }
- { name: "system-upgrade",              color: "8a44cc" }
- { name: "fluxcd-update",               color: "8a44cc" }
- { name: "longhorn-update",             color: "8a44cc" }
- { name: "cilium-update",               color: "8a44cc" }