services:
  # postgres:
    # image: postgres:16-alpine
    # networks:
    #   - internal # Assign to the custom network
    # volumes:
    #   - ${BASE_DOCKER_DATA_DIR}/dockhand/db:/var/lib/postgresql/data
    # labels:
    #   - wud.tag.include=^\d+\.\d+\.\d+$
  dockhand:
    scale: 1
    container_name: dockhand
    image: fnsys/dockhand:v1.0.38@sha256:20cc19f3af54e373ba8473377b04bd883f8a697027e151a81b4ba6c9f3c4e288
    restart: on-failure
    networks:
      - network_internal
    expose:
      - "3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${BASE_DOCKER_DATA_DIR}/dockhand/data:/app/data
    labels:
      traefik.enable: true
      traefik.http.routers.dockhand.rule: Host(`dockhand.${BASE_DOMAIN_0}`)
      traefik.http.services.dockhand.loadbalancer.server.port: 3000
      traefik.http.routers.dockhand.entrypoints: websecure
      traefik.http.routers.dockhand.tls: true
      traefik.http.routers.dockhand.tls.certResolver: cf
      traefik.http.routers.dockhand.middlewares: error-pages-middleware
      wud.tag.include: ^\d+\.\d+\.\d+$$
    # depends_on:
    #   - postgres
networks:
  network_internal:
    external: true
  internal:
    driver: bridge
