services:
  # postgres:
    # image: postgres:16-alpine
    # networks:
    #   - internal # Assign to the custom network
    # volumes:
    #   - ${BASE_DOCKER_DATA_DIR}/dockhand/db:/var/lib/postgresql/data
  dockhand:
    scale: 1
    container_name: dockhand
    image: fnsys/dockhand:v1.0.52@sha256:53529151a01a0866638bd870aa78cb2f2d1fff9a6bc55c60b2e30fe600957726
    restart: on-failure
    networks:
      - network_internal
    expose:
      - "3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${BASE_DOCKER_DATA_DIR}/dockhand/data:/app/data
    labels:
      traefik.enable: true
      traefik.http.routers.dockhand.rule: Host(`dockhand.${BASE_DOMAIN_0}`)
      traefik.http.services.dockhand.loadbalancer.server.port: 3000
      traefik.http.routers.dockhand.entrypoints: websecure
      traefik.http.routers.dockhand.tls: true
      traefik.http.routers.dockhand.tls.certResolver: cf
      traefik.http.routers.dockhand.middlewares: error-pages-middleware
      # Register dashboard DNS record with AdGuard.
      adguard.dns: "seb.local"
    # depends_on:
    #   - postgres
networks:
  network_internal:
    external: true
  internal:
    driver: bridge
