stores:
  yaml:
    indent: 2
creation_rules:
  - path_regex: ^clusters/[^/]+/(kubernetes|components|secrets)/.*\.(secret|sops)\.ya?ml$
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan
  - path_regex: ^clusters/[^/]+/talos/secrets\.sops\.ya?ml$
    age: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan

# Compatibility with previous version of clustertool:
  - path_regex: ^clusters.*kubernetes.*values.ya?ml$
    encrypted_regex: "((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))"
    age: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan    
  - path_regex: (^|/)clusterenv\.yaml$
    age: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan
  - path_regex: (^|/)talsecret\.ya?ml$
    age: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan