[tools]
oxker = "latest"
viddy = "latest"

[settings]
auto_install = false

[shell_alias]
ll = "ls -la"
la = "ls -A"
gs = "git status"
gc = "git commit"
k = "kubecolor"
h = "helm"
t = "talosctl"
gto = "gitops"
ft = "forgetool"
tcl = "talosctl"
badPods = 'kubecolor get pods -A --field-selector=status.phase!=Running'
badFlux = "flux get kustomizations -A --status-selector ready=false"
stopAll = "mise chart:stop_all"
kRes = "kubectl rollout restart deployment -n"
vK = "viddy kubectl get pods,ingress,configmaps"
getPods = "mise chart:pods"
sebDC = "docker compose -f docker/seb/.doco-cd/compose.yaml"
dcLogs = "docker logs doco-cd -f"
kHighRes = "kubectl get pods -A --no-headers | awk '$5 > 0' | sort -k5,5nr"