---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-fam
  namespace: minecraft
spec:
  interval: 30m
  timeout: 25m
  maxHistory: 3
  # enabled | warn
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: minecraft-java
      version: 35.52.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gatus:
      group: games-minecraft
    global:
      stopAll: false
    credentials:
      cf-restic:
        bucket: "${CF_S3_RESTIC_BUCKET}-minecraft-fam"
      rfs-restic:
        bucket: "${RUSTFS_S3_RESTIC_BUCKET}-minecraft-fam"

    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          main:
            enabled: true
            protocol: tcp
            port: 25565
          query:
            enabled: true
            protocol: udp
            port: 25566
      rcon:
        enabled: true
        type: ClusterIP
        ports:
          rcon:
            enabled: true
            port: 25575
    
    resources:
      limits:
        memory: 2Gi

    plugins:
      # vault
      - 34315
    modrinth:
      # - bluemap
      - placeholderapi
      - packetevents
      - holomobhealth-packetevents
      - holomobhealth
      - chunky
      - lagfixer
      - customdeaths
      # -  malts
      # - virtualstorages-backpacks
      - virtualfilter
      # - storagev3
      - auraskills
      - auramobs
      - clickvillagers
      # - smart-spawner-plugin
      # - coinsengine
      - thegoldeconomy
      # - towny
      # - axenvoys
      # - axrewards
      # - axvaults
      # - axtrade
      # - axplayerwarps

    configmap:
      plugins:
        enabled: true
        data:
          plugins.txt: |
            # plugins to install on server startup, one per line.

    workload:
      main:
        podSpec:
          containers:
            main:
              imageSelector: image
              probes:
                liveness:
                  enabled: true
                  type: exec
                  command:
                    - mc-health
                readiness:
                  enabled: true
                  type: exec
                  command:
                    - mc-health
                startup:
                  enabled: true
                  type: exec
                  command:
                    - mc-health
              env:
                SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
                QUERY_PORT: "{{ .Values.service.main.ports.query.port }}"
                RCON_PORT: "{{ .Values.service.rcon.ports.rcon.port }}"
                DISABLE_HEALTHCHECK: true
                SERVER_HOST: '{{ printf "%s" (include "tc.v1.common.lib.chart.names.fullname" $) }}'
                ENABLE_RCON: true
                EXEC_DIRECTLY: "true"
                ENABLE_QUERY: "true"
                EULA: "TRUE"
                GUI: "FALSE"
                OVERRIDE_SERVER_PROPERTIES: true
                VERSION: 1.21.11 # LATEST
                TYPE: "PAPER"
                # PAPER_BUILD: "138"
                SEED: 569475130819 # cherry blossom village seed
                DIFFICULTY: easy
                MAX_PLAYERS: 20
                MAX_WORLD_SIZE: 10000
                ALLOW_NETHER: true
                ANNOUNCE_PLAYER_ACHIEVEMENTS: true
                ENABLE_COMMAND_BLOCK: false
                FORCE_GAMEMODE: true
                GENERATE_STRUCTURES: true
                HARDCORE: false
                MAX_BUILD_HEIGHT: 256
                ENABLE_AUTOPAUSE: false
                MAX_TICK_TIME: 60000
                SPAWN_ANIMALS: true
                SPAWN_MONSTERS: false # wife is scared of creepers blowing up the world.
                SPAWN_NPCS: true
                VIEW_DISTANCE: 16
                SERVER_NAME: "Family Friendly Minecraft Server!"
                MODE: survival 
                MOTD: "Welcome to the Fam's Server!"
                PVP: false
                # minecraft:normal
                # minecraft:flat
                # minecraft:large_biomes
                # minecraft:amplified
                # minecraft:single_biome_surface
                LEVEL_TYPE: minecraft:amplified
                LEVEL: world
                ONLINE_MODE: false
                MEMORY: 1024M
                JVM_XX_OPTS: "" # "-XX:MaxRAMPercentage=75"
                RCON_PASSWORD: "${RCON_PASS}"
                USE_AIKAR_FLAGS: false
                USE_FLARE_FLAGS: false
                USE_MEOWICE_FLAGS: false
                DEBUG_AUTOPAUSE: true
                SKIP_SUDO: true
                REMOVE_OLD_MODS: true
                PLUGINS_FILE: "/data/plugins.txt"
                SPIGET_RESOURCES: '{{ join "," .Values.plugins }}'
                MODRINTH_PROJECTS: '{{ join "," .Values.modrinth }}'

    persistence:
      plugins:
        enabled: true
        type: configmap
        mountPath: /data/plugins.txt
        objectName: plugins
        readOnly: true
        subPath: plugins.txt
      data:
        accessModes:
          - ReadWriteOnce
          - ReadWriteMany
        targetSelector:
          main:
            main:
              mountPath: /data
            mcstats:
              mountPath: /data
        volsync:
          - name: data
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
