apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-github
  namespace: renovate-operator
spec:
  discoveryFilters:
    - xstar97/home-ops
  provider:
    name: github
    endpoint: "https://api.github.com"  # optional, defaults to https://api.github.com
  image: renovate/renovate:43.104.1@sha256:4cd17e16873f200370add2d4f790b3db7406ca16ca904f5d29ac0d13e5c726fb
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  githubAppReference:
    secretName: github-app-credentials
    appIdSecretKey: APP_ID
    installationIdSecretKey: INSTALL_ID
    pemSecretKey: PEM
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: renovate-webhook-token
        key: token