apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-github
  namespace: renovate-operator
spec:
  discoveryFilters:
    - xstar97/home-ops
  provider:
    name: github
    endpoint: "https://api.github.com"  # optional, defaults to https://api.github.com
  image: renovate/renovate:44.111.5@sha256:4e93eeb826c8a8e3bf7aa8243172c4c95f5297b85af86f5bee5085911221ae00
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  githubAppReference:
    secretName: github-app-credentials
    appIdSecretKey: APP_ID
    installationIdSecretKey: INSTALL_ID
    pemSecretKey: PEM
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: renovate-webhook-token
        key: token