x-healthcheck: &healthcheck
  test: curl -f http://localhost:3000/health || exit 1
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  drydock:
    scale: 1
    image: ghcr.io/codeswhat/drydock:1.4.6@sha256:d44a8c4695d0c1f57a78285edc3ddb4de6c62277bb592a68e3599a268cff3c0a
    container_name: drydock
    restart: on-failure
    environment:
      DD_SERVER_TRUSTPROXY: 1
    networks:
      - network_internal
    expose:
      - "3000"
    healthcheck: *healthcheck
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: true
      traefik.http.routers.drydock.rule: Host(`drydock.${BASE_DOMAIN_0}`)
      traefik.http.services.drydock.loadbalancer.server.port: 3000
      traefik.http.routers.drydock.entrypoints: websecure
      traefik.http.routers.drydock.tls: true
      traefik.http.routers.drydock.tls.certResolver: cf
      traefik.http.routers.drydock.middlewares: error-pages-middleware
      drydock.tag.include: ^\d+\.\d+\.\d+$
      drydock.link.template: https://github.com/getdrydock/drydock/releases/tag/$${major}.$${minor}.$${patch}
networks:
  network_internal:
    external: true
  internal:
    driver: bridge
