---
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
endpoints:
  - name: Cloudflare
    group: connectivity
    url: icmp://1.1.1.1
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
  - name: Google
    group: connectivity
    url: icmp://8.8.8.8
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
  - name: Quad9
    group: connectivity
    url: icmp://9.9.9.9
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
metrics: true
storage:
  type: sqlite
  caching: true
  path: /data/data.db
ui:
  title: Status | Gatus
  header: Home-Ops
  logo: https://avatars.githubusercontent.com/u/9399967
  link: https://github.com/xstar97
  buttons:
    - name: Github
      link: https://github.com/xstar97
    - name: Homelab
      link: https://github.com/xstar97/home-ops
remote:
  instances:
    - endpoint-prefix: "talos-"
      url: "http://${GATUS_IP_TALOS}:8080/api/v1/endpoints/statuses"
alerting:
  gotify:
    server-url: "http://gotify:80"
    token: "${GOTIFY_TOKEN}"
    default-alert:
      description: "health check failed"
      send-on-resolved: false
      failure-threshold: 3
      success-threshold: 3
web:
  port: 8080
