---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-phpmyadmin
  namespace: minecraft
spec:
  interval: 30m
  chart:
    spec:
      chart: phpmyadmin
      version: 9.3.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 30m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gatus:
      group: games-minecraft
    global:
      stopAll: false

    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        hosts:
          - host: phpmyadmin.mc.${DOMAIN_2}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: general-le-prod

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                MYSQL_PASSWORD: PLACEHOLDERPASSWORD
                MYSQL_USER: bluemap
                PMA_HOST: minecraft-bluemap-mariadb.minecraft.svc.cluster.local
                PMA_PORT: "3306"
