kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: github-app-credentials
  namespace: renovate-operator
  labels:
    renovate-operator.mogenius.com/allow-ref: "true"
data:
  APP_ID: ENC[AES256_GCM,data:TZDQdhUeAyREFPwr,iv:p+hJcam/xdn9otwQgxluBeOVnvF2iEKJ8Q6yiX4B+74=,tag:dmDElnpkeav1Tz+kgaap1A==,type:str]
  INSTALL_ID: ENC[AES256_GCM,data:3TUP3TDVEYwEFqC6,iv:AH/qlvWVBiFU4KOV9C7Wmzf7p3vsjYwf1tZr8gkPSyw=,tag:uBpKvmnTD79ibo6m2LAVOQ==,type:str]
  PEM: ENC[AES256_GCM,data:Dd+hGzfJMMpMsm6Rc7cUEbqBU9o1OR+wW1vt2Yo/cdDVspafLaJCbnO5I0KHhKEV4ydGhqSyieN+8Y6RbQ4kzSgIkNTHbCf7EkQA9BFzVcwiF91gXrePo8XoQRkxPtugFDmcDRH+EeZKvnR9fvxMdVNc6VDIw+sRqWGy6UfwlvTHOo++HF5kQz8/5juUPc0Vn/pCKBgSApTOjfinie0wMSGehsVmMbij3FwheZWI2dmH0z+Iy+kJSp1YuOJdTJP7cizkuSbMV38GRMTRwl9T6md5CYgsT6RtKFDE3+apUZTAL8ALkyzSdThqmG8hYNQIXMuSO6yWZDaPZvELqxgpoY5Mkb5q8BlnWeraZ8KRY7cOU3h0Q75vxwSj1JinM0PrEBgLI+zURtQPci09L/gvIgs88Hqp028VeVScaAxp/pJpUebJ8E1Of6wcs+na5vFeUXc7k34ug4kGbkMtu3jWjXbR/EF9iEnu2F3ZaO6nKR2U6KZe8QZ/QAjz9fNVYLfzsval6IOut8g4G1ZrnbdD+AiTXsUGJ2/w8vnVoSzRS+kBapr/2FWULqcj1i9NnInim9yRmHyKsha4CCZVhxXHACB2C0w016nZawhkCgxxjUrMZe/0QpeHQgnKywY6S2JIwjuPguEJlISAM1eBqECOqFmIlXRxw6Lhl4ICsErtwgvmmnY2dnRf1/VBX/RYNaKYClSMyj125ADvLNaa/Kj3mygcr663hjEIR8dG0k+O/yZVntsfQ8ECloxOGYTe1Ypky5RHI3P/cf2gvq8k9fyU4u06KCOXjBEoekL2K3Ou3DCJA5+DSvdFhCQZrCPj4eCL4FlPorfhA164tu5fRHRmprNzbwBLK1IT45uOMOFJKjvxxsng1yWFR7owTcG85ZuJjbB818ohURaHROx8FiqBd2VfoB0ZyCZnqzF3whoBncmhFYRxk/APDxXFDOTz5+Of+dQylWlF4IJQ6TdB58AXTwRac82Hupo0ebowEySaMnER3NwbN6pTaw7u407onUQM6H82fp9nIIGoGQbSsK9S6L4Rq//BZtIRuugL6UIjbbRmheepx05l0vVRz5MRVNh9SFPTS5dfp2Miy48RHqaRUugtCCtPhUovA46FK03A+ZhkM+9PTT5xuABCjStLOtQVK9DF7qBOXtmInxCsIlFD6VHpFncfqh+VwdHkyVrdjIdMsdzlTm1m/gE3lcovp7zpRAPXlRFZRKqWXRzVwQk7vqT1G42IlmJ4jdyV9U0TatKqABmdMAHnVcXmMkc52dU0FI/x5m8uqlrRbiZM5J00Z8dtrqNbmO89Ut3k2iRUmE31SJB5p34StVrKMwPKUz4aZSMNN9HIytwh7wF7lSDVXktSNLLGT4HHUQdLk06lNfy6pfTsDB2ubplMNNSZN+FX7YsBDoEMbu6XnfyvZTCEpDGePZlmNRll21SNc9/QNnjWEpwI2iYEPbPrDu4XBWD0rkxl6/sQjh5+XmjWTUA8G1Y9ln5eRD4p2MoPXRHA0GP4TrhaY9/RQv5BmX6haJNMIf7vBvEn+e+CuE31uu58VlSn2Wf0dL0sI61YZYpBBOWN+E8iPyR/xMlxVNbqxHoefg4Im172ldlYbxt9Aaq5Kit6/LjQ0dAREyEnQbce8xH5FE1bRdDeVbDgs9yiBL+YkGmyDO+Sm86ImpNd0ExvaQ1iyPuEb4E/pskgR/E+gJGAttlUJ3wx95vUbX8va0dZyaAz5iKoz8WUjQfjip1WN0QvpOUIkOI5m2j0n39dLfIc7bU0YG3ASIMw3EDzeVVhfJge0ZSOcjdxeNqGwXvnpX3tCGLXG/0YmIfEMxqMOPt1vaXgNSZpWbHgm1YaXUsiVgnPDIegqSLut4faxveEzvjFzDglOX2rpb+aWORxm+GsgL5v/mkN/1Vxm0m/qgaq884HTBZjPHKMoXpLvC9VJJwUEDSsWPj45BZvVSzxySc76EtW7lxEHbb9VH0IAVDuWvFsRJUWVvchOy37EVOh1aZp/Dq/Z6XGw5ibjHuIDtVQpE41H1Jbm75BvuLsZN1WgGis//d69Dzeb21+Ax5jRd+p3wyPNh8UYbHIup/lexNnkQc6j6rpW7vlhYjRqGo4R1UWrjhcb0UIt2qr22hQ7tUnlVpsuyEWi5eZelluq34+mQ0BtF+iWfex95L30Ghqz+dcbDSeFqnB77/ETXRCmBY4JT5wDKkQld3uNtNUEomKO21UQQ4CK9Wv2ZPl3HuZm92SLBxFSek8S0lrt9PjkwydDs0FS4xd7nWRVx1fAwjyJRBvbMjI3Shr6yLEtRBqO1eER5/h8ZdS8wYZM4hPoKTHtOEThrG9+mLWD0fk1/lP2MlGrIlpznZn4jn+Xb7zUaB43LKgVT/XMXlwkvAA0Hst301GHomNUy3QfQwS2WBUB/6I20l/CKweANcl22Vdky3gv8cek4cM4X7mO1ymM1TxRKMAHkVmyI+1a+9JRmx49o0g/36fiNXlM6YTg+jyst0xRfDOOCZ0YISwno1eNwkCc3Nie4i3Qe1TGowFAWX9w7PG0jgBa2Dp3t7ozk8KIymFaKrY4bwaVXwDpPXmaYQJlTPj/GUGpN2MnMxfnNzyHQrmqvyX0e7cGGylUjqm0fX82qddAWOCYr4URNmD+O2LlrX1fCk74S4aOBJxwmqaGQf8WjzUxrpAPUyEP3/NSAy4DDebLTSRx9oshOStMVeNOBSTtYTSlGqrpGHijtxRWTrUx125r2j5YeuwxexajUgw5rkqe5FaB0+Pd3NfT2A3MFFQi9xy1p6K6xXespCsglCwTGMyB9UYaavwmp6wAWEvslUPEp6qRdDEWDJ1Ent1y8NqfXLZfcPkkTLOeHB1Zv+xqOV0aXFzIZY/FDOo3xx5ztZtpjztrbzYzm/9AYocrLKi6Z5LZcWsfs8rZ0JH8VwuTnOP3gjCdQmPlDeZLjzJ/WcEWX0D3CgccNS/7xCFr8BPDd85v6o5/BU/Ang=,iv:ibNsTMW/p+wCi8R0571qK2w9KdxNUjjVgWVquXKrC68=,tag:hR/bvqThMaE3amHzJoFdzA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1STljbitPQ0pmalY1aDA5
        RTBlSUQxZ2FObjBTRUtOdXZKcGhJelhPOHlVCkVqSFQ3QklvMk5Gb3lGTGc3b09N
        RlNncFo2Vm1Tb014VzhsM0pBdVFnQW8KLS0tIDh5blh0UUR2bWZOTU1DcXRaY1hG
        cTdUaEUzZzAyczRWck1VQ1VucXRXQm8KyvpC/5g9Wt91JtqmPN/48jlhIZMF5UVm
        UQrXfdpkFeKzcSoBcTiWY0z6g7P553sjtWPH0wdHUC5rIe1y+X3ELA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T08:21:11Z"
  mac: ENC[AES256_GCM,data:cns2BmPHTynq3KORWhH58EHqMduYXW90Rw0b0+IP5GMwTpd/Rv9WKIl+rnovEifndn0M04EYri3IurOc/P56mgU/qjdg5Dcn0UgsSAr0W6RluCe9OQTUy+Y44qbbx8ff0pEKDJjMFchcDBDA3AblXlXCGHhmzPjZIGbwsBymrL0=,iv:Lxp9QwkUa7VkiWMcHIn0M54XxEnzzWmonDHmQVLWaYc=,tag:JaH926QfUvFmr7mjOxYS/w==,type:str]
  mac_only_encrypted: true
  shamir_threshold: 3
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: renovate-webhook-token
  namespace: renovate-operator
  labels:
    renovate-operator.mogenius.com/allow-ref: "true"
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:3lGFFnm+XZ4O+y9wVYKuvpM1KfHKgO0IPC+nS/3kCukUtqeNJxIySxC/e2tcOkL/aW3EP2KIVaVmOM5FYHPang==,iv:NFh+VPtHd5lLgjWl67XZFbbRPz64g6Oh0BUQcnC+PfA=,tag:GTJrM1Uhxf1pR2g6KChQ1Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1STljbitPQ0pmalY1aDA5
        RTBlSUQxZ2FObjBTRUtOdXZKcGhJelhPOHlVCkVqSFQ3QklvMk5Gb3lGTGc3b09N
        RlNncFo2Vm1Tb014VzhsM0pBdVFnQW8KLS0tIDh5blh0UUR2bWZOTU1DcXRaY1hG
        cTdUaEUzZzAyczRWck1VQ1VucXRXQm8KyvpC/5g9Wt91JtqmPN/48jlhIZMF5UVm
        UQrXfdpkFeKzcSoBcTiWY0z6g7P553sjtWPH0wdHUC5rIe1y+X3ELA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T08:21:11Z"
  mac: ENC[AES256_GCM,data:cns2BmPHTynq3KORWhH58EHqMduYXW90Rw0b0+IP5GMwTpd/Rv9WKIl+rnovEifndn0M04EYri3IurOc/P56mgU/qjdg5Dcn0UgsSAr0W6RluCe9OQTUy+Y44qbbx8ff0pEKDJjMFchcDBDA3AblXlXCGHhmzPjZIGbwsBymrL0=,iv:Lxp9QwkUa7VkiWMcHIn0M54XxEnzzWmonDHmQVLWaYc=,tag:JaH926QfUvFmr7mjOxYS/w==,type:str]
  mac_only_encrypted: true
  shamir_threshold: 3
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: oidc-secret
  namespace: renovate-operator
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:g8KlKDqdgIoP5f/OfosAy8joQQsHd8urI+JKjnjUEFGnTY9O7TUc4W8nlJNQpTAzEW31eQE+9hn3Oh1VU7FGZQpbZSXYwxLHIXK5DT9mgSrGGlFqmVl9xN1/kivbI9MSJDvfeobcbLhqvsSqGY4sc43Pi4TVL1XLUTzChiIgINs=,iv:cV6yJDmV89I0N3kDdKybfU6OB6HTb4J1QGZsF5a15dQ=,tag:puSWloKn47qqu2JhnhA72w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1STljbitPQ0pmalY1aDA5
        RTBlSUQxZ2FObjBTRUtOdXZKcGhJelhPOHlVCkVqSFQ3QklvMk5Gb3lGTGc3b09N
        RlNncFo2Vm1Tb014VzhsM0pBdVFnQW8KLS0tIDh5blh0UUR2bWZOTU1DcXRaY1hG
        cTdUaEUzZzAyczRWck1VQ1VucXRXQm8KyvpC/5g9Wt91JtqmPN/48jlhIZMF5UVm
        UQrXfdpkFeKzcSoBcTiWY0z6g7P553sjtWPH0wdHUC5rIe1y+X3ELA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T08:21:11Z"
  mac: ENC[AES256_GCM,data:cns2BmPHTynq3KORWhH58EHqMduYXW90Rw0b0+IP5GMwTpd/Rv9WKIl+rnovEifndn0M04EYri3IurOc/P56mgU/qjdg5Dcn0UgsSAr0W6RluCe9OQTUy+Y44qbbx8ff0pEKDJjMFchcDBDA3AblXlXCGHhmzPjZIGbwsBymrL0=,iv:Lxp9QwkUa7VkiWMcHIn0M54XxEnzzWmonDHmQVLWaYc=,tag:JaH926QfUvFmr7mjOxYS/w==,type:str]
  mac_only_encrypted: true
  shamir_threshold: 3
  version: 3.13.3
