kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: github-app-credentials
  namespace: renovate-operator
  labels:
    renovate-operator.mogenius.com/allow-ref: "true"
data:
  APP_ID: ENC[AES256_GCM,data:h7NmBKgVu7VAu7A5,iv:2Ck0RzRmZNTiE1izgE64OQFMrUFSKlXa7YKttIFW3d8=,tag:SIV2Bjqw5JehYx6qCrp4RQ==,type:str]
  INSTALL_ID: ENC[AES256_GCM,data:wczCqX4mxO4MmesF,iv:1zFeVo2vfCCuAEd1DAZn/1v24Yn1iQ5jxhYDBPxVYKQ=,tag:1yffap2mON1m/VzVIMN90w==,type:str]
  PEM: ENC[AES256_GCM,data:UR4L06uRBS5NwnJYEd/T3HZn7BT28sH+sE+te9PWOHP7PY12LpWFt67XzGL7OE+LeHf1g3VgTqYK4gFG38xBd8vWRBC4UwCnBB4h8mDeF0uV71QJo2pmCVokhWKIrBv5R0LYfMRe8C4PeumKRiPKGjTiWD3/DC/oXk1OlwV33cn0QjHhJUl4uDm8+YCrt0DMjUiwpRSQRjUAR68j4REQqiB1hbW1IYb2XkBN+J1tCFnbtOQig60sNL6wGfPeT4gV99xjAGRydTiqtv5woXP+wi7hwDiJSJLhV3bkkfVek8sJyim6CLWST+aQB23SSkNAE3oc9kBX+PYZK+076VCImI5sMAnqUAvRp6rH56R+aeue+PyheYlS3xz3qz6O6oTLTXLm7sfNaOz2Lr0xr5c3MF38Z7wzB1/m+m0Uxr4aqd5zCOOvirs0oDQNWCRC2ilFSxt5ngv9/82tASU7asLUxJuB4lAIpVYFg7abfuuEJ1qEuU8ITEZpBCoiUC18s2HVKHEOIhfRlAwu7rDH11T7fKtzdPAMDsM1gA/jlx8jNGkuiwTfd1Y7v4J/qCn0nFJ/J9jfvXhiSCQDNHty0sykD29mSCmw0N/fmjmHZLINZtd5bB4GrSAvBm5Y6m4YU4SHUD3VAQvDlHVEMMq61X9rF9IwNU5EMk07+byoFyQDwBTwjAa9h9X+FCwqytodBtkvWGX5MkQRAm/O2/G0Wwnzs1+NyMnFAEwEDxpVW3UL6YvEHTYFXBiN8Wauyw81tK9Wonwffp1VN6GAmabW9j+2xtH8BfAc8+dzGl2F0ws1ilFydcIDRPdpqdCw1j1KG+6hPhRTSbwjDLt2yBaf3FDPIFvl96tY+ZM5uoKf99zRun6TNvNmTG66BjboB8zO6Hjsc6bKiZEIxUEeJ850dPsxODX9X+Us3TqL3Ou/+DAS5ETMKeQik/BHziED6+3Adlf2u1mlVBsw6mQMDdgDcDkLBpfMfRwD9d88Nyw/x1W2tSOHh1jfudgV/wIwjuUEVj/yTol8DrLXmPyNtP8cbARMduBgw2VFefffg0dnG1eTuSrtyhjzJnN/PrMI6QvzQsTaTQmVxUlNK4bS7zs5Jr6uJj7BRKWlR3lkCzeoAUx5/gh9PzAdc1YjMdOXm7edoxvM6ZIsLJg+9tLsurngAdA+jTPjdg23Kz0aNRl6qqNjpkfkp90VN0AeknxQqE48gxlRMXCbq1/xXVT01qG1WxVppBSF9w9RIvfbC/1LkeON6F/+uSnHok3Ugb9eDSEiaUYpc3mJBGgQEsw5KZebCBtmERmZnup026wfYDTZltnH7scUuID3u2Rd8apsX6hvPbdGGiBpaF5e6jXqU+lKCvaKpCmcPzihb/x0EZkDMc15EibRgiNma85o7cgW3AdifmJopr/VkH48rvZ4RNCRDE4zIsMUlYVka69nEdQNxv7u7E8UQZJMjcL6SzMKCG+z84riWNAlQzU3+kOlJe/fvxkugzJDFHDVy5+qeHVpYjrGR7pgZLwQtVDJ0uO3LlSfDKLjqi5d7qgHzuSq5Blj4JYoeyEulGu7BJ2yfyHUlLOEktddJB0L65Q/0MNBl63DCMSHyiTxd5Hv9sSDSwngjxl9l2S0I46gyH4h8x0wht6C/ZupioCVkEIi+2uq+g9dx7uqAHVSRMAmrFTHPF7/hdhTxdQCuN3fhqOA8HNCG1msiVTGKIf8sRGlzMNQUhvHb5CZtzvDSQWyOXO2JpOvoJCDeY48tKz6DoznaOoP1ynxMesccZ+irfR7T1QyQidlMV0Ubtet9gTwfpJbIwSaNc/ddPzLy+vP769iEhwWj+SbGukhmSfsNYUSDQ6Bzt/BLrqvw8Qb9Ug7DFRfs1UNzH0RfjKCZFwjZJNo2+gdnhRNkHejFJGSOPSC5lc4fPePYuWZ0rAy0oj4NHm9ArOmKDfTwoI8eZKiYfPvg6uTx1O/BAR/zSotjD+4bHVxhJwj+Urp07B2sZxg4Wxn4VJTtsiuvp4XU+17Hws5dBARvwXGlWcKHgmLwb6Xvy9iXpafP7GW2U0y6gLYgiT+4jvZpAV2JWPS6Flp4lgOmm19Ipkg8A56zZmYvCOHk4oZtY1ASH/34JBZw/MYt+S3Df57b3Kfv/i0+nyOX26rh2oDrB03vr6yq57HXCQpHsMAF3kyftgMin06ROe+oT6Nos52xCKxQL0s2LT6yPGwvIc4zqbnUtB3eTYiuJfwjja+V6qM6pa/Y5sxJfuJZzWKzZvDYzNXuMf8a060m6ioR+XIQjKa5hdbthZgBMywrOLnnUQ9/qZe0hJIPFx3Zb0pOj5FpYx0FVJoDZUfsMwE0vEchI0fM2qP7VFrRdJXn+bPz2oCAIocTgE4osG71KrOeIixRyPSc70v8ZZLLnQcemZYhwyrM0keJOcAxCv5DgVUHNmOaUb0guH1elJAoLOAHRS578D9GxFqJYKrx2LNA5ebVcfXeIEXlmMn+uyaj3UBqiPOiR4BNCK15O2hdw+0yF6BFYrm4Ok+EFcLItC7YT7kak8dQeaRlF0Lvl/L+30XSrF8So6jR3iR7D2xyYtzvvxWsq0XKiie71vg9BUPrTVMTE9omCVeZq3Tx5TxekUBW6ra7qlqQRPLG+gfB4brag9ExVrZDfbn4r1Jdm2yOXktx4FzOBZ5MRIo6TO7id05rFUKv4D+wbFRbA01sP7EPaB/EMqUNKMcbMTYVNLIV7BXrbwUyh7uIC0DJvsCy1uGZrl8PyApxi/CJT7cK9kQ3qKw/PT/QqwImqyYwh0CR/Ii9eY9uqNZ4+SGlOWeX6zzwWHQddgt5nmOV2BdvP4vYSe+HVf+9+yFpzg/myRSdw5cg49WrM/ULw8wMC6H7M2Hjqzmjig8oslNFEcEpDBvb/+yMnvMShAoSmSGpWAwnpkOce3Piyrx3FYvaV4Ch2LxwAUuuhlTQE1RyhBplOaK3l4cKYXUvg9rWaq62/2+JuF7MWbb9EY=,iv:p7lRJ5z/1A96fkG2mlHHjatVu5P8cPMqHEhnU4/tQCI=,tag:meopziEwDGfuKVANAlBNmQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOEt0Q2FjK0hkUkkxcjdK
        aWJnaDM2aGZsb2ltMnBoMUVxdUFNODFNTnhnClJNMStGcldsMVBHZDVycjAzMnlV
        THBxbzdnOU5wNnNsMDFJWXc4TzhGdTQKLS0tIDZSTnF0VjQ5MWVxS3FKSXpBVmJX
        V3ZlSGphekEraTB0QVlVNndMeEJ4TkUKtoSjY1j4P8htBx2euUcdZhzxr8ezD/e0
        ghjAORy943dXuMGX3pLlE6W1EE8hcRd/8SAyqz4qLlHuiLHX/mLHqQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T13:39:49Z"
  mac: ENC[AES256_GCM,data:Q4alO9Gcm275y1UP7txQIrPoY7kHcbVKtzNCPX4Q+7pHxnMEHzu19uOgW2kGhk8Y34oDu1QHKRPh7MDKU6q2BDjbNi3jjPYuO0EaY9n8YohBo7DZrxiHnn4xmdTSvbk3IdV/C0WuhAdari0+ZOEFUO0lMQFlqaUv9/PYK3ynzyk=,iv:ZC1vEpAMKcmi5z/6u0NEvLdh8TjW3upEV0ZLJ0yFMLs=,tag:JtubEulyrR+9zPDuMK1vug==,type:str]
  mac_only_encrypted: true
  shamir_threshold: 3
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: renovate-webhook-token
  namespace: renovate-operator
  labels:
    renovate-operator.mogenius.com/allow-ref: "true"
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:/oUCuARltvNWaqf/uAZ5LrYqVVrxUtlu14BoPqu9uA5lqarvllFwTkUNFUO6/Bznn9qKuMh4FubIFXOTVtjqdw==,iv:YSyoAVRePPhU0lf15DDqrH80XYukAjste0uypodHxKs=,tag:cGXGWuYjJwK6aVS5v16skQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOEt0Q2FjK0hkUkkxcjdK
        aWJnaDM2aGZsb2ltMnBoMUVxdUFNODFNTnhnClJNMStGcldsMVBHZDVycjAzMnlV
        THBxbzdnOU5wNnNsMDFJWXc4TzhGdTQKLS0tIDZSTnF0VjQ5MWVxS3FKSXpBVmJX
        V3ZlSGphekEraTB0QVlVNndMeEJ4TkUKtoSjY1j4P8htBx2euUcdZhzxr8ezD/e0
        ghjAORy943dXuMGX3pLlE6W1EE8hcRd/8SAyqz4qLlHuiLHX/mLHqQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T13:39:49Z"
  mac: ENC[AES256_GCM,data:Q4alO9Gcm275y1UP7txQIrPoY7kHcbVKtzNCPX4Q+7pHxnMEHzu19uOgW2kGhk8Y34oDu1QHKRPh7MDKU6q2BDjbNi3jjPYuO0EaY9n8YohBo7DZrxiHnn4xmdTSvbk3IdV/C0WuhAdari0+ZOEFUO0lMQFlqaUv9/PYK3ynzyk=,iv:ZC1vEpAMKcmi5z/6u0NEvLdh8TjW3upEV0ZLJ0yFMLs=,tag:JtubEulyrR+9zPDuMK1vug==,type:str]
  mac_only_encrypted: true
  shamir_threshold: 3
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: oidc-secret
  namespace: renovate-operator
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:6/t7BsMwedVKnIC2zGjPTnp7B4ugaAo6d4G8b0Cc8mNRm/C/+DhOl9q65D0doAJIkrTHB3yKQgfRoUgRlgT6d46JA9+CpMrMi0UN/STC9W5mf7jZ4+MzIr5MQKFpWMwc3YjNVPwIr4uYm+IUHv+KfPyQh74jzW6Q9nDd2RkCL6Q=,iv:WSoKy5qm+3yWRm1jXnKOpKTFjNoZmdp2mk3KjNtBelk=,tag:RYpNdNTvsfmnY+O+YXiyTg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOEt0Q2FjK0hkUkkxcjdK
        aWJnaDM2aGZsb2ltMnBoMUVxdUFNODFNTnhnClJNMStGcldsMVBHZDVycjAzMnlV
        THBxbzdnOU5wNnNsMDFJWXc4TzhGdTQKLS0tIDZSTnF0VjQ5MWVxS3FKSXpBVmJX
        V3ZlSGphekEraTB0QVlVNndMeEJ4TkUKtoSjY1j4P8htBx2euUcdZhzxr8ezD/e0
        ghjAORy943dXuMGX3pLlE6W1EE8hcRd/8SAyqz4qLlHuiLHX/mLHqQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T13:39:49Z"
  mac: ENC[AES256_GCM,data:Q4alO9Gcm275y1UP7txQIrPoY7kHcbVKtzNCPX4Q+7pHxnMEHzu19uOgW2kGhk8Y34oDu1QHKRPh7MDKU6q2BDjbNi3jjPYuO0EaY9n8YohBo7DZrxiHnn4xmdTSvbk3IdV/C0WuhAdari0+ZOEFUO0lMQFlqaUv9/PYK3ynzyk=,iv:ZC1vEpAMKcmi5z/6u0NEvLdh8TjW3upEV0ZLJ0yFMLs=,tag:JtubEulyrR+9zPDuMK1vug==,type:str]
  mac_only_encrypted: true
  shamir_threshold: 3
  version: 3.13.3
