apiVersion: v1
kind: Secret
metadata:
    name: renovate-webhook-token
    namespace: renovate-operator
    labels:
        renovate-operator.mogenius.com/allow-ref: "true"
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:nIWLtXL7xZttnv+HDBiVeK5xp3sefDjfbXGixQdX+662+a23ychyo2M0AMiYUr8kLM5F+tkw4N45tP1mFQMfBQ==,iv:/t/tmYoLhJnry2v2VwT8iqXpgNDbmMEfKt0x2Nhlzms=,tag:KyQFy3GgVNFk7YX5hhkulw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMK3JmSlZvQ1k1N09vNnFF
            UlM4ellZMHc5YlNzRllmeStpV2VkOXVtNVJVCk1GZHNVb2pNaGdOZ2c0ZnFTbzJD
            bXF0YmRLdFFWbElYcm1nOTg2QVZKWGsKLS0tIEpCR3pQYlg3L21KcWJNbjk1dXVl
            ZE9uZUVTdU9LaGY3Sk0vSTNGWG1sY0UKTNWLaKVPGQINWf7jIIURHKbtu0tcpaF/
            m0I8IAdRTiJBfl7c9Ah9RRHIsq02KjlFU/M2+oIwKa6EGvDy98AOhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9mu36rp8zc4fy9pexe2mxlu4rk4ef3gg4tts6j0x5svsctdx5yscrk8rx
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-21T03:27:21Z"
    mac: ENC[AES256_GCM,data:B7BfTPRHi7ZwaYt6CJpuGpPvAJgUZZhG0l46ul5jbqJjjspyucn1B9NjbIOLDdhzoUhITnxAJ53Tgz44e0g3a1hFxlwYwTDNJWwQV9u9JnWFt+hIiClQG7U23R4fkANu5fdPwUAwIVzFZ8C5sjiwkFiWGh56O8zY5RENkmCEiiI=,iv:eaIA3Buu06yZyQWkN/17ba1NyWuxxTpx5GIdkXHe0lY=,tag:LfYRFb9GsbjXEorlKRmAIg==,type:str]
    shamir_threshold: 3
    version: 3.13.3
