x-healthcheck: &healthcheck
  test: curl -fs http://localhost:8080/healthz | grep -E '\"status\"[[:space:]]*:[[:space:]]*\"(alive|expired)\"' >/dev/null
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  code-server:
    scale: 1
    image: ghcr.io/coder/code-server:4.124.2@sha256:726c75e330d99c9e6545ff1208042ccc3d97465cf24cdb48b304d111a43cd441
    container_name: code
    restart: on-failure
    networks:
      - network_internal
    expose:
      - "8080"
    healthcheck: *healthcheck
    volumes:
      - ${BASE_DOCKER_DATA_DIR}/code:/home/coder/.config
      - ${BASE_DOCKER_DATA_DIR}:/config
    labels:
      traefik.enable: true
      traefik.http.routers.code.rule: Host(`code.${BASE_DOMAIN_0}`)
      traefik.http.services.code.loadbalancer.server.port: 8080
      traefik.http.routers.code.entrypoints: websecure
      traefik.http.routers.code.tls: true
      traefik.http.routers.code.tls.certResolver: cf
      traefik.http.routers.code.middlewares: error-pages-middleware
      wud.tag.include: ^\d+\.\d+\.\d+$
networks:
  network_internal:
    external: true
  internal:
    driver: bridge
