services:
  apprise:
    image: caronc/apprise:v1.4.1@sha256:25e0577915c2f06233ae1dce077f05c0fc9ba4f0ea89de5aee18a32b2ee9a75c
    restart: unless-stopped
    container_name: apprise
    networks:
      - internal
    ports:
      - "8000"
    healthcheck:
      test:
        - CMD
        - /doco-cd
        - healthcheck
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    environment:
      TZ: America/New_York
      APPRISE_WORKER_COUNT: 1
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$
  
  doco-cd:
    image: ghcr.io/kimdre/doco-cd:0.89.0@sha256:38717384d9c46e366fd217e0104467f5fa62ebc72f7586f899645f92de989315
    container_name: doco-cd
    restart: unless-stopped
    networks:
      - network_internal
      - internal
    ports:
      - "9080:9080" # Webhook endpoint
      - "9120:9120" # Prometheus metrics
    env_file:
      - ./secrets.enc.env
      - ./doco.enc.env
      - ./base.enc.env
    environment:
      TZ: America/New_York
      HTTP_PORT: 9080
      SSH_PRIVATE_KEY_FILE: /run/secrets/ssh_private_key
      SSH_PRIVATE_KEY_PASSPHRASE: ""
      SOPS_AGE_KEY_FILE: /run/secrets/sops_age_key
      APPRISE_API_URL: http://apprise:8000/notify
      APPRISE_NOTIFY_LEVEL: success
      DOCKER_SWARM_FEATURES: "false"
      DEPLOY_CONFIG_BASE_DIR: ./docker/seb/
      PASS_ENV: false
      POLL_CONFIG: |
        - url: https://github.com/xstar97/home-ops
          reference: main
          interval: 3600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
      - /home/xstar97/.ssh/id_ed25519:/run/secrets/ssh_private_key:ro
      - /home/xstar97/home-ops/age.agekey:/run/secrets/sops_age_key:ro
    depends_on:
      - apprise
    healthcheck:
      test: ["CMD", "/doco-cd", "healthcheck"]
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    security_opt:
      - no-new-privileges:true
    labels:
      - wud.tag.include=^\\d+\\.\\d+\\.\\d+$
networks:
  network_internal:
    external: true
  internal:
    driver: bridge
volumes:
  data: {}
