services:
  magicmirror:
    scale: 1
    container_name: magicmirror
    image: karsten13/magicmirror:alpine-v2.37.0@sha256:8deb9a5c9c30608c4abcfc350c0a7964224227653985e883c9207e783971161e
    restart: on-failure
    networks:
      - network_internal
    expose:
      - "8080"
    environment:
      MM_SHOW_CURSOR: false
      MM_SCENARIO: "server"
      MM_PORT: 8080
    volumes:
      - ./config.js:/opt/magic_mirror/config/config.js
      - ${BASE_DOCKER_DATA_DIR}/magicmirror/config:/opt/magic_mirror/config
      - ${BASE_DOCKER_DATA_DIR}/magicmirror/modules:/opt/magic_mirror/modules
      - ${BASE_DOCKER_DATA_DIR}/magicmirror/css:/opt/magic_mirror/css
    labels:
      traefik.enable: true
      traefik.http.routers.mm-server.rule: Host(`server.mm.${BASE_DOMAIN_0}`)
      traefik.http.services.mm-server.loadbalancer.server.port: 8080
      traefik.http.routers.mm-server.entrypoints: websecure
      traefik.http.routers.mm-server.tls: true
      traefik.http.routers.mm-server.tls.certResolver: cf
      traefik.http.routers.mm-server.middlewares: error-pages-middleware
      wud.tag.include: '^alpine-v\d+\.\d+\.\d+$'
  mmpm:
    scale: 1
    container_name: mmpm
    image: karsten13/mmpm:4.6.4@sha256:a6a15505e9c90287c7a41abb990779e7ff8b215589abf40772c2d1dcd41f2b5e
    restart: on-failure
    networks:
      - network_internal
    expose:
      - "7890"
    environment:
      TZ: "America/New_York"
    volumes:
      - ./mmpm-env.json:/home/node/.config/mmpm/mmpm-env.json
      - mmpm_data:/home/node/.config/mmpm
      - ${BASE_DOCKER_DATA_DIR}/magicmirror:/opt/magic_mirror
    post_start:
      - command:
          - /bin/sh
          - -c
          - |
            chown -R node:node /home/node/.config/
        user: root
    healthcheck:
      test: ["CMD-SHELL", "python3 -c \"import urllib.request; urllib.request.urlopen('http://127.0.0.1:7890', timeout=5)\" > /dev/null"]
      timeout: 10s
      start_period: 60s
    labels:
      traefik.enable: true
      traefik.http.routers.mm-pkgman.rule: Host(`pkgman.mm.${BASE_DOMAIN_0}`)
      traefik.http.services.mm-pkgman.loadbalancer.server.port: 7890
      traefik.http.routers.mm-pkgman.entrypoints: websecure
      traefik.http.routers.mm-pkgman.tls: true
      traefik.http.routers.mm-pkgman.tls.certResolver: cf
      traefik.http.routers.mm-pkgman.middlewares: error-pages-middleware
      wud.tag.include: '\d+\.\d+\.\d+$'
networks:
  network_internal:
    external: true
  internal:
    driver: bridge
volumes:
  mmpm_data: {}