x-healthcheck: &healthcheck
  test: curl -f http://localhost:9100/metrics || exit 1
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  node-exporter:
    scale: 1
    image: quay.io/prometheus/node-exporter:v1.12.0-distroless@sha256:2e043fb8c976c68bbce62ed8b407c02802068f966f8c9411f7e78a47f647a2eb
    container_name: node-exporter
    restart: on-failure
    command:
      - '--path.rootfs=/host'
    # networks:
    #   - network_internal
    ports:
      - "9100:9100"
    # healthcheck: *healthcheck
    volumes:
      - '/:/host:ro,rslave'
    mem_limit: 128m
    cpus: 0.25
    labels:
      wud.tag.include: ^\d+\.\d+\.\d+$
networks:
  # network_internal:
  #   external: true
  internal:
    driver: bridge
