apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:qls7ZrvAYbaTr1OO5LCvgu8Z8dznDALOPT9Ordjrajgtf9w4PeMcUtsVVduuc/tUx7AHweuqYpPRxFA99SHOavnG+/w6WLomWd6YzvqNJljJozLo7LYzspUQwNuw/IJ+396PJtfyjIJCK2iVWRIonYYT7IXk5y2H/0cGwg==,iv:3v9j0zoPYSwJD7Dx5iMfLESFH8M7a6GjwDCSdkwI5iY=,tag:sj/314DTFsjjasAbq2chXg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNElESWZhRy9LcE1zWFM1
            L0lXRUdmTlRZRVQxczI3UHFJTmxGSTRTRkhjClhjRFRmL2R0WnBxSUEwaU9iajNx
            ZHBFRW9kNmZydDFPanQzMDljVUpNclEKLS0tIGp3WTBiV0lSeE42QmZ2NTJ5OFNu
            c1NuRm02MnZmU2V6cXNDdis0enlsV1UKdWoD1S5ABPyMVgIO7SvcDlNamWiTqw3H
            LMf/YS/IJNxC1SFO1WpxMVHO+Imi1OjatxJq86vQCdiAvcHwni67rA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9mu36rp8zc4fy9pexe2mxlu4rk4ef3gg4tts6j0x5svsctdx5yscrk8rx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T10:18:07Z"
    mac: ENC[AES256_GCM,data:wc3YqSo2oThQiZHFtyHcj3vue6HzhY+8gWYhOzb4sWcTqn47TQgWaaQbfbwdblxK3ZCzj7YYiYLgmolk7Kw42m+CXqGD5wYF0Bq9YOU6rDZSVkmbcr8yYXRplK9PZPTUsBVo8i5R7pLMjuaWZ/WiOSg1Be0z4G/Ng4Dk82m7AAs=,iv:7IcXHOT8mHDx1jdB2PX+2alVGDTMUaf478KyYru4HF4=,tag:Ew2RnHa2jWTKpfcpwb4CYQ==,type:str]
    shamir_threshold: 3
    version: 3.13.0
