apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:mPmkoAfzRbNg53qo8a1umx3EZYeOSzD6kVrpOVr2QX2GygbTaXszNjNZtKnwsEfX26IXWx5cHjlALZ1Mavpveb7uzS7K5Xr6jVqSNAKZSmAOwDpBcgokqx4UqsGXueS2ZfqhFyvAHBalybD9pruI3knzydBUQIPP52pUsw==,iv:jbPRB4cGd8BPbTyPk+YzLZVLQf/hORU4ZuFACuCvP4E=,tag:KvTtWtnXJ6UFl2xAV0ZJ+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeUljRUNHR3pEZEh1Z3Y3
            N3U5ZGZkTG5aendRSmdFb0FvSzAvNXJ2cndRCjc3aTl3UHR6TVFqNjJ6RGw5T1R0
            L01QT0JvMjZmdVVlRVJvRFE1RnJMK3MKLS0tIGVoNUptZEdVM25uL24xdGRSOTIr
            SUF1S2FCRVM2dVJhVCsrdUFyamozMW8KVlD6xrfWwx2/XUGbh/dBm74dI9O+/SCo
            3XjUBokl2qIV8KWQkRp4WjWdXM7A7RDLhxtrvZ8Olw0UCeahJFzs+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9mu36rp8zc4fy9pexe2mxlu4rk4ef3gg4tts6j0x5svsctdx5yscrk8rx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T23:36:01Z"
    mac: ENC[AES256_GCM,data:lKgW5irVDbGHtXl48wuverO2vaTNf2nfLa8fTo8vSwZNquRgRwjXhl785HCD2e1Yg6vyMhLJkEPEwZJQwbZYceqqFg0hohcWAFGikPFNtEtDS6pUjurUXmCoQS8l/iNGLinoIACbBWhbgEGjjVDTyxS+GhMZNVOg7/Kn19ynqGI=,iv:kfQIGRBuoxDRNxDks5nRNYNvE9kEsUScYxnDNpM7pmU=,tag:dLU9FeSnPCl6ARoQ/w2wdw==,type:str]
    shamir_threshold: 3
    version: 3.13.1
