apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:VB69di9azcCuRMyN/nZ/+yBuTx/IdtoFiJ6Odo8zmkRwbuCEIn/ruPWnHWUpQ6wfu7wJ7uXll04V+Z7F7shLgl2ihsvxVdJTnGFtZfzwdCLAMN3WowngXc9TYvxf56Q85HD3TDSdqcKmGv9HKxyPgFQIlud+HgiBPOrQkQ==,iv:t4hQnvlUkWeASvKSu+KVcNvaSrMli8nnDwuwZXCyW0k=,tag:UnZlkXbZMp1Rwm4JhwUm/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOTM2aW45RzJXY0Rrc291
            MWxNR29Ka2lONXhNcGpRRG1QVHdhRHZ5WHhZCmtydiswaURUT0JkbjRyLy9kUlgw
            cEV4Ulk5OGtLemNYZjYxTnJhVGJTK1UKLS0tIC9ab1BZRVVGZnZDVHhOL3ljOEdK
            WGdscU9TcVNCSWpGVGZsWlpIUU9DdWcKD52EBwyjsKzGoKxVkUGJ7kTk39/ia45R
            fqBEoQTEo+8zaoDIXJaKYfJTEmMF2+VYdlYk5DJP+LQxizb6Kqj9oQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9mu36rp8zc4fy9pexe2mxlu4rk4ef3gg4tts6j0x5svsctdx5yscrk8rx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T03:00:37Z"
    mac: ENC[AES256_GCM,data:yS63iQq+Gs6DvYIl+l8n8pDXAVsw5yNNbVEOGolizyDokUZNZVCh4bB4OVSm2mp2bCbHFgQowUKhYgJV9X2aabyEdXAqWtaepv7bQ1gzmlGbnNiaY7Jd0jEbfi0ntc4L5m75VHTNv565ok6I1VyZBkAaVOkD2CuUr1fe7QHDoZ8=,iv:tkn1jzfurqXK7Lw2BAdZtQ6mAhM6ME5APGbGswZajq8=,tag:aK5f23vOlEN/Fjm+QrWACA==,type:str]
    shamir_threshold: 3
    version: 3.13.1
