---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crosswatch
  namespace: crosswatch
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 18.6.6
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 30m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gatus:
      group: media-utilities
    global:
      stopAll: false
    image:
      repository: ghcr.io/cenodude/crosswatch
      pullPolicy: IfNotPresent
      tag: 0.9.21@sha256:3cfafbee01f412d00ca1198ab9c55229a0e2a41ebafb3a08df809a56420a86fc
    credentials:
      cf-restic:
        type: s3
        url: "${CF_S3_RESTIC_URL}"
        bucket: "${CF_S3_RESTIC_BUCKET}-crosswatch"
        accessKey: "${CF_S3_RESTIC_ID}"
        secretKey: "${CF_S3_RESTIC_KEY}"
        encrKey: "${CF_S3_RESTIC_KEY}"
    securityContext:
      container:
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        runAsUser: 0
        runAsGroup: 0
    service:
      main:
        ports:
          main:
            port: 8787
    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        hosts:
          - host: crosswatch.${DOMAIN_2}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: general-le-prod
    persistence:
      config:
        enabled: true
        mountPath: /config
        volsync:
          - name: config
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
    cnpg:
      main:
        enabled: false
