---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-stats
  namespace: minecraft
spec:
  interval: 30m
  timeout: 25m
  maxHistory: 3
  # enabled | warn
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: app-template
      version: 18.16.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gatus:
      group: games-minecraft
    global:
      stopAll: false
    image:
      repository: ghcr.io/xstar97/mc-stats
      pullPolicy: IfNotPresent
      tag: 3.3.1@sha256:342655b591da08ff44ad9df6bdb4352085773f99410f6b21e2b8eff62ab8ba17
    credentials:
      cf-restic:
        bucket: "${CF_S3_RESTIC_BUCKET}-minecraft-stats"
      rfs-restic:
        bucket: "${RUSTFS_S3_RESTIC_BUCKET}-minecraft-stats"
    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsGroup: 0
        runAsUser: 0
    service:
      main:
        ports:
          main:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: "external"
        hosts:
          - host: statsmc.${DOMAIN_1}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: general-le-prod
    mcstats:
      family:
        server:
          sources:
            - path: /data/family
              worldName: world
        data:
          documentRoot: /config/family/public
          eventsDir: /config/family/events
          statsDir: /config/family/stats
        crown:
          silver: 2
          gold: 4
          bronze: 1
        client:
          defaultLanguage: en
          playersPerPage: 100
          playerCacheUUIDPrefix: 2
          serverName: null
          showLastOnline: true
        players:
          inactiveDays: 365
          updateInactive: true
          profileUpdateInterval: 3
          minPlaytime: 60
          excludeBanned: true
          excludeOps: false
          excludeUUIDs: []
    workload:
      main:
        podSpec:
          initContainers:
            update-config:
              enabled: true
              type: init
              imageSelector: "image"
              command:
                - /bin/sh
                - -c
              args:
                - |
                  set -e
                  {{- range $name, $cfg := $.Values.mcstats }}
                  
                  # Create instance dirs
                  mkdir -p /config/{{ $name }}/
                  
                  # Write config.json
                  cat <<EOF > /config/{{ $name }}/config.json
                  {{ $cfg | toJson }}
                  EOF
                  echo "Created /config/{{ $name }}/config.json"
                  {{- end }}
          containers:
            main:
              env:
                PORT: "{{ .Values.service.main.ports.main.port }}"
                INSTANCES: '{{ keys .Values.mcstats | sortAlpha | join "," }}'
                INTERVAL_SECONDS: 300
                
    persistence:
      config:
        enabled: true
        targetSelector:
          main:
            main:
              mountPath: /config
            update-config:
              mountPath: /config
        volsync:
          - name: config
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      mc-java-family-data:
        enabled: true
        type: pvc    
        dataSource:
          kind: "PersistentVolumeClaim"
          name: "existingPVC"
        existingClaim: minecraft-fam-minecraft-java-data
        mountPath: /data/family
        readOnly: true
