---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  interval: 30m
  timeout: 25m
  maxHistory: 3
  # enabled | warn
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: stirling-pdf
      version: 9.20.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gatus:
      group: tools
    global:
      stopAll: false
    credentials:
      cf-restic:
        bucket: "${CF_S3_RESTIC_BUCKET}-stirling-pdf"
      rfs-restic:
        bucket: "${RUSTFS_S3_RESTIC_BUCKET}-stirling-pdf"
    service:
      main:
        type: ClusterIP
        ports:
          main:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        hosts:
          - host: stirling.pdf.${DOMAIN_2}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: true
            auth:
              type: "authelia"
              internalHost: "authelia.authelia.svc.cluster.local:9091"
              externalHost: "auth.${DOMAIN_2}"
          certManager:
            enabled: true
            certificateIssuer: general-le-prod
    persistence:
      configs:
        volsync:
          - name: configs
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      tessdata:
        volsync:
          - name: tessdata
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      custom-files:
        volsync:
          - name: custom-files
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      logs:
        volsync:
          - name: logs
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
