---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana

  datasource:
    name: Prometheus
    type: prometheus
    access: proxy
    url: http://kube-prometheus-stack-prometheus.kube-prometheus-stack.svc:9090
    isDefault: true
    editable: false
