apiVersion: v1
kind: Secret
metadata:
    name: grafana-operator-credentials
    namespace: grafana
type: Opaque
stringData:
    service_account_token: ENC[AES256_GCM,data:RUQUXPXVCtLXu9B4T46r0Pb5DDFCxlj2ceWEhCimGNGa0pK7SLw0ErbmA2b7LA==,iv:2iet1vLIyP04pZUjAwcC3OImraXdKaJSL2iNwIBjk50=,tag:/CwB+ULKrqq/nc//hPgnsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUFFGWFJ5VEpRU2xQZEF1
            K1FRUFJrZEk1ZWxTV2FXQks4L0xzMHM3YzNJCk9ONjFFZ2p4MldkUjJsNEQ1ZVBE
            RzNxNzFsYktUWDZYWlN0LzlhNExzancKLS0tIEx6VnY0M082Yk9HVFZ3L25TNWFm
            KzFVbmVlRE91YTJrWnZHNDcxbEJrQlEK4ctWb06XS7iulQRRL2M4dtml0nogd5fE
            nbt/u9FO5Bd5atF93NaNrkeqho2GKQziKrq+0Nh8WA8TX0gwFGSvWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9mu36rp8zc4fy9pexe2mxlu4rk4ef3gg4tts6j0x5svsctdx5yscrk8rx
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-23T12:56:25Z"
    mac: ENC[AES256_GCM,data:TEF5F+FsstyMFMPheta/YZDQRgZ7bctfzygigohZqu16s+D9Y0EOflC7p2ejT47feGmKb1LIPDoudR4HiIJzLAWamtMV7BoR6Rlj3aXdC19A2auEYv9gZ9gdw0LVRVBTosIOEHiVdg2Oa+JBDDLk1VReq7uPudJEaNEVD2yAuIo=,iv:AJk2+jdLDBvx+t3HjUXSAb2PHydwDogmPO58TvxBnNI=,tag:usQhKWht+S8J2lx1bMmqIg==,type:str]
    version: 3.13.3
