apiVersion: v1
kind: Secret
metadata:
  name: grafana-operator-credentials
  namespace: grafana
type: Opaque
stringData:
  service_account_token: ENC[AES256_GCM,data:AoaU8A0W+xR3uxVz823JsxVcuNtogpp41nY6zmJSKODzRyBBx9OLhPGq27pd/g==,iv:7kBPyt4bS1GiO+6C9aIX2OGU2pmUv1F+O85aUPOugJk=,tag:sTQtMaZ496l0PfDvFGLhCw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaUEyTzZPTlBjYWpONlBw
        dGR2NEF3YU5xYlBRbGx1U0Vua1g2L2g5ZlYwCktROHhUQ0tWWldocWxaZTlkYWhn
        bldlZnhxeWdySTMzSGZpQjVoRE5wTU0KLS0tIEFzN21ZRXllU3V0RFE0TmhNQitJ
        eHZNNEk2WlZodGM1c2lUc0w1Y3I3U1kKz1bv9lgWgWb0Cxbn4h53+c2wBGEA6Vv7
        my0f+2t8aEn8SM3nvP8B72aqg4T3rvekDyOc3T2kQAcUhjoXRIAYMA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T03:24:43Z"
  mac: ENC[AES256_GCM,data:99IfPu2EXau93YHKpscDOtC4xrQsI9oebUba+/i6u7yIFUv+YCYua9UF+yE9ppuJSQ7wMk7BSE/ETIQaLrU5+VEdYHsJJA3GnS1ZPkbP9TQ+31Jw0V1U4uPmKvt2AD/QVE7QrVdtzOuNbUfu5uXHkwu1BGorQpF/QsmZQIzTktw=,iv:WExZNjPmVfKWkMJ/3slnu98I0+SkpfCTj08eYVanXrw=,tag:6ZoOpx+qfPDC2tZlJNc3XQ==,type:str]
  mac_only_encrypted: true
  shamir_threshold: 3
  version: 3.13.3
