---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
spec:
  client:
    timeout: 30
  service:
    name: grafana
  config:
    server:
      root_url: http://grafana.grafana.svc.cluster.local:3000
