apiVersion: v1
kind: Secret
metadata:
  name: grafana-operator-credentials
  namespace: grafana
type: Opaque
stringData:
  service_account_token: ENC[AES256_GCM,data:ps5corTHSkcDrw21MUYki+9P1V+u5w/lMll0gHBvJjXKtyjdBa/czZfnUgBD/w==,iv:6+TYFQE0+vlRrzCc/awyfzwEXfjtKl1tTJII4mnTF8g=,tag:IyB5L+AUeLGbrFGLYt7i7A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VXJ3ZHo0cldxbGgrSHlD
        WGtHWFJsRExHZlo2T2FBUnRoSWVTdDNFcWdjCkRRaVRkWUUwcThzTW5McGZaNy9u
        aEE4WEhPUE5WQmc1L0cyNDZSNUV4WkEKLS0tIFZQUzFHTEhORTN0cWtqcmJ6aHgx
        clpIVHV1R3RhdGo2VWN3RmV2R0JVYmsKXNbG89gFX7/dI2RhS+rsJWx56hChucto
        shArkxb0GQzwuqxlAPKmkljpi5nOrCPgdpdh/PEFjxdtpLZdzOgLng==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-29T07:05:05Z"
  mac: ENC[AES256_GCM,data:lOER3dHmmwXrTYwOYcDGxkDsqiPGEle3BBysgGEAWpyhNj0peXcLTG/xhP2PbNp26j5ynZL/XJV7h+P8KOZhwmNCCYPqHNWmk+EgdpchnlyaZdJobFN/XtYAlqcs43M4gMyy9sqdvTepJm9sibsbyJg232o1F4LcE43elMgeLSg=,iv:fSLtIP+KpDwwXc01bSCbESYVOpoMqsvwiJGzBn01vi4=,tag:0PGNXCqtN4I1w5gvRp5FSg==,type:str]
  mac_only_encrypted: true
  shamir_threshold: 3
  version: 3.13.3
