apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:s+xxcOgkXEWJX/ZdjYTErHHzb9PwbgEfvXjCaoRM48g=,iv:XJa9kHxu05ZQWZqM+s4Mhvjj4tqIFwsCqfMA4VNU4FY=,tag:m6jW4IsQeSY/3Y3LmTi91Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucVE3eHdYVjA1THZGeFRY
            c3VPUjRSbTFUUE9HQ0JJcHFTZXJIOWQxb1RFCjhEWDJaSTFESHhJM1M0ZzR0VGFk
            R3VYWnRYRXZKQyttQnhReG1RUGp5MVEKLS0tIGt2K2kxOXUzc3hqdUo5b29CQ0t3
            WERDbjA5dDV2WmRpSEkzek1jQkQ2Z28KqN7JJ4wZCakYYNzjnj5HKxfwpvn79wsT
            BwhI3Zxmh8adoAals0/OwQiZ9EzFjQyZXpbAOKIaM01RR1ugzDF2ow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9mu36rp8zc4fy9pexe2mxlu4rk4ef3gg4tts6j0x5svsctdx5yscrk8rx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T05:20:20Z"
    mac: ENC[AES256_GCM,data:OHb1mFQbWMH2a7a6rvYbqIuv9PBT54bYIBj6GY/ie0kRbp5YzMhryEcSzqZZ3SLJh7KYADhUlkHbAMvmYi0IsbmSNn0JLyJnhXQeq+LraJVTjVd/FeXnuw4xB1B7j4jiTMt114cS/goPxPelzGNYrYBgoAmJf7/9TjHhb9B2VJM=,iv:ApaD4pIVblV3G9kIveBfzpJpJEX92Ux5FypXRjJkDXg=,tag:D3n72Ek2pjsYRhOzFa7ENQ==,type:str]
    shamir_threshold: 3
    version: 3.13.1
