apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
  namespace: flux-system
stringData:
  token: ENC[AES256_GCM,data:v0fKRNxdZPX6hwaB81Z+bHZBtVKbZVWcDJO6qYsCkjI=,iv:iWx9NwAqwsQGIvLGTqmtlBlaEFfCNJXmN6xRHjHU6RQ=,tag:S2ZOcS+TZddFoPxihEd8lQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUVBVZ1dOeVBEL3h1MnJ5
        TXZGNytVUUVVdDlFZjRyRWFSSTd5dnRSc2w0CkcwaEUxekJ1Y2VNK0VQcnlVdHFN
        T3Q5RmVUOVJSZDA5K3g2cmVTdGwzd3cKLS0tIFZVcWlzUVdZV1VzZ0ZXc2ZjQlNV
        M29EYnh5ZTlTdnBlMDdDNENHVUZUYjgKE//7YFACvUI0FdMsnd2ch6uCHo8fwb5o
        PurUwPaLBk/3o0PlsOR9h5AcE3atylA+ciM934JPFN5byr9eS4WgEA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T08:21:11Z"
  mac: ENC[AES256_GCM,data:D8AwFVBHt8LHnGV5e8A9owHXxW9qKbPVprj37RumApMEbjIoelC3LsqSdxiu1a9j03RJDNLPWnr6mdAEx87pNiui5zNbfoTc0bgtqVrv/PoXM0LB/VtTLj4cnh8Q2yVd7FwOZlnaO0H7X+qOFrbI+Cfq2q8Z4HnKpJYtcEVWJek=,iv:hP1BeQlnnoLNQmwQ+pJWWG2A6rkre5+2rQMIRa2UOb0=,tag:SpE941yEB/rQtGgG5VA/mw==,type:str]
  mac_only_encrypted: true
  shamir_threshold: 3
  version: 3.13.3
