apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:EeiIwpYyprrNuW0DEZO8Bj58Nlz8gb3AtONgTtsdBJQ=,iv:00J2ahHUaRovsNZAnaW591xPq83pL0fATwSWRdhMqZw=,tag:tlpLwlqsVmWiW44viKFddA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByU21rbTFGNENsVjhBRG9w
            cFhiRm9mVU1vNFZJSjBLaXpKY2pHdDdYZlJvCjNDR3J3ajJZZ2RJd1hhVVhtZERo
            NG1xdTRTcmx4UDhjanNNYUpKN3dRN0EKLS0tIGdFMUorNG1PbElJU1JLV0xZdGRT
            dUJKK1JSZHNXUkVJc3A3eXBWdUJJM0UK0U55JkSmSVPp2ufKcBaYDreZso0nUaMR
            zjLhTSadS531xt/ns8HHYwatFHBAZuhoAThpXjMytIJ8der2t8/NdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9mu36rp8zc4fy9pexe2mxlu4rk4ef3gg4tts6j0x5svsctdx5yscrk8rx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T04:49:54Z"
    mac: ENC[AES256_GCM,data:aNm7zR+p2Rueq/d5+8VGVLggso8wt9zxVknks6KjNDhZ2keTWcMjXTu/eWbD2DE/7jxX5pWhjNXd1P5b2E3+lDgDe2kEF1Dgs+6g+vgZ4O3z+FpCZelxbEH0/GMCf07BwuYrqAQmi1+cyZJKrz2yVbMwsSVmGuW431Fsu8bVNVE=,iv:lsApSRONXiUBJC35+g+Lc59u+f8wsW4Wwneru5I/oMs=,tag:v99JAn9NMND4Mj277dHNvw==,type:str]
    shamir_threshold: 3
    version: 3.13.1
