x-healthcheck: &healthcheck
  test: curl -f http://localhost:3000/health || exit 1
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  wud:
    scale: 1
    image: ghcr.io/getwud/wud:8.3.1@sha256:42554d2cd50d5de7a47563170bd0629193dd1e086a1fd71d1ec10fc4c2409f5d
    container_name: wud
    restart: on-failure
    environment:
      WUD_SERVER_PORT: 3000
    networks:
      - network_internal
    expose:
      - "3000"
    healthcheck: *healthcheck
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: true
      traefik.http.routers.wud.rule: Host(`wud.${BASE_DOMAIN_0}`)
      traefik.http.services.wud.loadbalancer.server.port: 3000
      traefik.http.routers.wud.entrypoints: websecure
      traefik.http.routers.wud.tls: true
      traefik.http.routers.wud.tls.certResolver: cf
      traefik.http.routers.wud.middlewares: error-pages-middleware
      homepage.group: Monitoring
      homepage.name: Wud
      homepage.description: Keep your containers up-to-date!
      homepage.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/wud.svg
      homepage.href: https://wud.${BASE_DOMAIN_0}
      homepage.widget.type: whatsupdocker
      homepage.widget.url: http://wud:3000
networks:
  network_internal:
    external: true
  internal:
    driver: bridge
