apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: yarnl
resources:
  - helm-release.yaml
  - namespace.yamle
components:
  - ../../../../components/notifications/discord
  - ../../../../components/gatus/service
