apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-admin
    namespace: flux-system
    labels:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    userName: ENC[AES256_GCM,data:S9vAilw=,iv:UMkSFt+Pe/iN3awmQieMjacbBTGiA69SnsImIKJgY3o=,tag:xeO2saFM2LS+gpjWQeu7qA==,type:str]
    passwordHash: ENC[AES256_GCM,data:3wL0AK4HfDLfE2/lhf1C81QmPsLvWUE+7VXwFvUjgcCdUVjDoJPmxgNZ1rSPZ8edrU7ukvMYlk9QdE9L/rdt,iv:AfLdiIrVEdL89/BJWFv46tIQ0eE2RH/DkAh1/zc6BZM=,tag:RzCC8d3U7joWIPgEh0d4FQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZHZBUTJOZ3AwR0t5SlBY
            VnVjRWF6RExldkNESVhUTzNNY3BLQ1RMQlZzCjFDR3hPUTNTUDVLUDA3U2hERkNB
            V1NkOGZFQmRCYzhFbkdNWG04R3FHZGcKLS0tIGNnaTJYV3U3bjRFYkswTURUaUp6
            c3c1Sm03aE9aa2w3b1dxVHA5QXpHaU0KBwfBHZol+SDmv4FiU1Mw87lBJwiu8X9x
            40Qz/7i7qxhNn0aVNIq3GdW3ZA7eRE5tgzjLPSg05enO/HnTQcRgfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9mu36rp8zc4fy9pexe2mxlu4rk4ef3gg4tts6j0x5svsctdx5yscrk8rx
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-31T05:36:59Z"
    mac: ENC[AES256_GCM,data:EPMMGn3DGBw+FWuGQq3xb5LKhTT5nE7byHhlcxRePRiwEBfEKOo8B+xoxn5POUWNVINP+H4uMJfH7a3CpVpCAG5YBeKDzY52nsGAuiVJDFatZEaJrkal0DT1DgQUXl6PJjPAK/D1I8WZRREE5HSY31wMVfqYyTNWtJFGYlUY6V0=,iv:IHUAX9ZNKMfemE4LIvqtc249OJ0rnklvZX5Ig9L3kc8=,tag:0f4nRVIj9KUktWAQ0SPMtw==,type:str]
    shamir_threshold: 3
    version: 3.13.1
