apiVersion: v1
kind: Secret
metadata:
  name: weave-gitops-admin
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
  userName: ENC[AES256_GCM,data:ZdVDzic=,iv:BbbQ4X6/moWGHJpD1EjT4tfuI+lKRiCGKPgpXJL/qJc=,tag:u/je+YNy2pHOZY6jpKhagQ==,type:str]
  passwordHash: ENC[AES256_GCM,data:1JGBEcM3BoNv55NZUS7aLzswbittcbvUuj5Nx4Y4iePGDz2zDKK89DEdoXM8dY12VBpe55QWnxFh8oJMsj+s,iv:IAEQv30LBTeIfOeoUJpdhG/aOqo3TIurxmgsnzec/mo=,tag:q/y0OuTUSH/TLqtuLfBJog==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNjdnQWszODNyZ3RYNmRD
        cDhIc2ozOHFIUG1aVEt2bW44WTV2WFF1WGxvCm0wczRBeGNNZ3ErLzBMVWFiMExs
        MlFVK2x6OVlONjBHYkhmdlVSb2VsdlEKLS0tIFZlWVV2eE81SUxUSHVqY1JVMmFq
        UmtxRXd0RHdWNUFScU15Q0E1UVFVa1UKhjQ+klMx8YfunuSb+csLt/rxc5I5ezMT
        RaDk+MXm91+U9bJWvpeBrP2Z46kWMjlMRa3136ePYvfqcUYmA7wdMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T03:24:43Z"
  mac: ENC[AES256_GCM,data:A5+LwiGiQCwz3dTsmBAWUJrdrXL9yVvwuLTiMMz6Tqw74bM/+jvKfj2/253pdzHfdFwZ2Rw+F7YdsPrpF2CnLnaRxknpUKbyCEdYUyfNeErhCdwiUCb76iX4G8AXRR7e0sjfebq75OlYMWaiT6J0xUaJgw8R/OH8uMlDYVxGMXE=,iv:q7fDMGlrT6VNv1xBr1S8QjzBtTHCmwWXNvXvuEhljjE=,tag:NYAPDc+WJpoQ5V2wq8hayQ==,type:str]
  mac_only_encrypted: true
  shamir_threshold: 3
  version: 3.13.3
