apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-admin
    namespace: flux-system
    labels:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    userName: ENC[AES256_GCM,data:VoWFd40=,iv:V8MvUDaWh5YiJrtxLfcXk78g/NLkIbzllyjZq9htWP0=,tag:SR2f9i8QJ1BB9S9veuod4g==,type:str]
    passwordHash: ENC[AES256_GCM,data:bUkh8Bv3Bwhg6Rnh7NvdVAN4WNmuKck6y2ikl03p65cmTIY8w01+PETg6jobeFLywrJUg81uA6rRBhbmF4gq,iv:R0k1/wS48oyEi9rEl1n2fPEImyJ/huzB9mkNinlQmuQ=,tag:3L3KsQY2XrRNe5hEBTXLEw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3U0hla1pKTnBJWWN2MnpT
            RnpmY1UzbUZVb2lUTjJMdFFMNEVMMVRscnh3CmkzWEtLWDFHVC9ReHk2R3hUdGRJ
            LzhsSFZvS3V6QW9YeWRIc3FmTDFDOW8KLS0tIDhlcGFVdUZ3Y0VLY2xYMFA2aHFV
            RWtNUnl3VEs0R0R6UnBldm84dWJNbmcKdAqW4LqCsJYrilXx6VbTcF7LWsGQ7DPv
            6GqdXV/6fZKvFndA8bCcDUq3AG4OgFV9YOYCj8ymqipkqQFvoONm6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9mu36rp8zc4fy9pexe2mxlu4rk4ef3gg4tts6j0x5svsctdx5yscrk8rx
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-15T14:38:48Z"
    mac: ENC[AES256_GCM,data:DJk5r27a0O6raHTBCbqvvL4/EIyvvZLllqoJFmtXP7o1Dqu5Ca7dGY9U/QmVzd+CcAerEsOYPZ7fIHj9Xei5vrA8abE4ifjme4R5B9jGxlAjpJ4IybPo0pR8rA1RxiARYbIamG1RqYDqOQLJSija+uweopZQyy8HWUEb2CskkYU=,iv:9ITmE/yVdO/soIDtnQJ/it+E7uqtb8Z5qP3e3GT+4Fw=,tag:RkoMC4MXGxKTu3rUxSzQTw==,type:str]
    shamir_threshold: 3
    version: 3.13.1
