x-healthcheck: &healthcheck
  test: ["CMD","httpcheck","-t","5","http://localhost:6969/healthz"]
  interval: 30s
  timeout: 30s
  retries: 3
  start_period: 10s

services:
  amialive:
    scale: 1
    container_name: amialive
    image: ghcr.io/xstar97/amialive:0.0.3@sha256:5f619baba4cf073eece913c0be6ce2217abb816f6a403ff11ee079aef280e671
    restart: unless-stopped
    networks:
      - network_internal
    expose:
      - "6969"
    healthcheck: *healthcheck
    environment:
      PORT: 6969
    labels:
      traefik.enable: true
      traefik.http.routers.amialive.rule: Host(`amialive.${BASE_DOMAIN_0}`)
      traefik.http.services.amialive.loadbalancer.server.port: 6969
      traefik.http.routers.amialive.entrypoints: websecure
      traefik.http.routers.amialive.tls: true
      traefik.http.routers.amialive.tls.certResolver: cf
      traefik.http.routers.amialive.middlewares: error-pages-middleware
networks:
  network_internal:
    external: true
  internal:
    driver: bridge
