apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5sVLdrBnsi7UD9aAUXmO2rWuC5whhANTulp3baW/hbDrkZSeybXSYs6gtRfhvmgMJmlnwY3BP0nAMeBg6FJ6eUbXVONc8rxTykz0VJI6+J8XrbYojj1XesfB+uppiZtrkNFTvgPjtgAek4OqlZrf5aRX5LhejNI5Aj5+WtMRnUYuAvopUYDISYfh1g6qTEJBhGsuph61A89h35zcsE6YpeFga5CAvv+yFstqb1NDLihVmipmo5uwbr3QRa90XDh8n0LgQ7cdYUFhqPxX9ESPpoBv2Ske6uqAW7HS/8vF31CclNlFeo3YIQCTYnDWTSgZimXBypz4j9fo1gIqr6Dwkt6RdZx2BKUFdKZb6Z+6bVvQ4CT3BtURhU5cdifLvj5/,iv:2z4iHadbr5jTaQAOVroiN/gm70DsLKQdFEYEJUIuuwc=,tag:hLphNuF/681221UbZVSY8A==,type:str]
    identity.pub: ENC[AES256_GCM,data:qK6LL9Z7RAvASdAoPluJ184KD+ovZ/PyTmfP0N10yx2JplVHTnOqjGeii2T37PB69pIZJKx6phs8CBJenDlD3B7W9/b0CEjJW+peUbYHCti6elMrza6RT489nFkAF76J8tyRfwDXsw8QbfcT04iidc1IUG6ngicRbNUDOqIr6izUDPncOS7lTlwK4s0nSsFGevcyZknlYb89bWDuy8Yr+fG2h79E/h/MDpwZ9XQzfYoEuZEHEHuZE1Qp7yEvDDORftvGtNz6Lse8su5Quw==,iv:9iumsDcZtPZR1I0TLKAEnt+VWOy3iTY14ZMJl3ubhSU=,tag:5GzZ5tgbl+DwUlP/hUjNaQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:rYS5TR9+AFO+E0nkufWET7Mzx2NYTXBCDoc6EdEGnscTN8BNfXEaQp8unnOMXLbAf4FExX3fk3NtzkHDIfbbos+8QPCijzamIMaWtTmZ5fbsoCBrEx+eMxmA2jeLEnhmM6Q6yug9Fnt8RQ/7DzzQmD/VhKhSe+Yh2Ildf0xAwwIpNYtr1jIo9fRrhwoM8SLB9zLH2fkB2FYQAJam4tD0NbuJhamqapk4Kee3,iv:J/nH4IkFiD4xHQT3khwjxGra74tOClSNQTSBzephsgk=,tag:vfeqkGauMrTK/2K2bELFwA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYkRjc0E3aHJRN09GRWJI
            VFJTRUwycm5Zam9aajA0R3ZBcXM5YW9mSGowCndYaENiVGlGUjVoWHFIMVdvNFFT
            STNFZEhsOWlWcUEvVW9kWFYrTlpQTlkKLS0tIERJVGFUMWRQRHhxWHNYdGs1Mm8r
            YXZqQ0tPaFh3M1I0UUlyWEVibzBHQW8K9WvA4Fjg/usfK6LMtVdjnpWyGkq4KhSg
            ohH3OAeIGZi93rUZTL0OUk/c/TvHuErBNT2cCF5EUx4WtDwFgSWI1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9mu36rp8zc4fy9pexe2mxlu4rk4ef3gg4tts6j0x5svsctdx5yscrk8rx
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-20T13:41:32Z"
    mac: ENC[AES256_GCM,data:kklsEt4QXcL3r+InDbxmJJHyNfeMrE4IVBkgQ/25XAxAoej+YdrQKnsi2pPp9Q2fptbJ72Kb/p56/FOJ3MIkk2AQCxcDYTCEsfIn/loGV9/ZkmIU8CB1S9H37Ep7C8R71xnL2RuPUM2n9FlZI8L48bpJ+GOee3ju1MqyvUHtQLo=,iv:v2mlyroOSz//aU34+k9iuxs38rRax+di/XDUh8qm9FE=,tag:GTVlKi5S4viYRnGvTfp/Yg==,type:str]
    shamir_threshold: 3
    version: 3.13.1
