apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:gJOhdEqKPfiBzcaTHd88jMswNMgO4H94oAzc9uHjS04dRGEutUiQRq9GEJO51zVyrDG56QEgNm+EFDSvWUrSb59tjk2V07U0mCsxC01BfrJS5aBJ8xhSa8KeUKAS/VOcYja6GO+XA9BmDPxhVmY75H7FBs+xVSrBVJDOO7c4+LNpeDO+OWMa+Ut/RnMbr5bz5uZWpZcsxdEZ/+O8I2+pQSLyPF4ozOmiSHHQEoNHeo8hSABsf3SbtcJdmKS+1YGSMTb99XzdViRA9VI7T0UQ10SinBvOmKQVzwhe5Xkp+QUj3bRI9NZ8ZqbcevEDxsO+Q1uJ5yFQRTBJB5Viw+t8Zbn5xM5Yvf9TFQmNbvtVAZheYRPLl6qLzc43OM4NIwoQ,iv:D9IakaSKH2lNJ1GMo0g6IBFq8jnuPxqRJcdfNXELyjw=,tag:+084CFoMKr/5s1MEC9k81Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:8GL4DC5FxrCC6SRDqtRTTjzipi2KE+BjPCsZBtW6bLh5XzhhJwz2Ms5f6Db/CLippnVjTblJRYOs0dPe8HiVm+DsF6Gemg8tQ4BUeqV2VQY1LHg6ukMw8tUeoEstpCS4tXWGu9XO7lPIXWIcfJvCiUw7J/n4MR26DRLAYQN36nu3Gd2g3/uv2DPoTdfjeOX9yyRdI+MJnCmafJAYinBBrrpYgv/ktQrQwRI6wKwzdzUcE11aw0y+tEy1AivETjq7l9zj2BKVQEXqO+2hzg==,iv:rC9bHs7Nai5JafRXd2hd43hrm/BDXx1WMqLlZzbm5HY=,tag:WZeLbbTW4+AhERUQhLTTSw==,type:str]
    known_hosts: ENC[AES256_GCM,data:A5pUKN0xwuxEb9AGyyJ9ovcKjQKdzoHEV1KwziEReqb5U9ziqZsdW60vtCpR8A/xYx/4HtbbQmTeLFpeDx+TnSks9KalD4OnoNMZGUPdm7M5NA3HG+CdLSqkhz60E+PbdRpIvGxIVle9YuuCVwU873VusPr4RgKT5HrPLexWS9FSXJnYaDi0xDx59AiGLsADdJvLfCSExmcCP6xJglU0gSiaeRo/6jqKTYid,iv:asAHHjWS26wQMLF5RfiaIm6ywJU1fLbngo8h2vBJK0A=,tag:oYdogN0CDHG/9xQKK10afw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBelVQZnhUeUs1S1hCMzJ5
            ZHFFb09aZlBPejh0SlFBSlpDcWdET3hqTEVJCkhyMkxoL1NYY1E5K0VsUDFOZVpF
            cTZURmtXTlQ2YStGanlxclJhOVZOTTAKLS0tICtXSUUybXFGUnkrSytuMlZlVVdK
            dGpYdEhOZDhaVjBhRXp6RDc0MDJlWFEKOenbjj8P+u5ieUiJ8cloIkDlIRyviQIe
            6NI4BPNZ6udxlBYhsxwMIyQoF/5578EVCfaXFn2DB/DNArFdy9i2MQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9mu36rp8zc4fy9pexe2mxlu4rk4ef3gg4tts6j0x5svsctdx5yscrk8rx
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-10T20:08:16Z"
    mac: ENC[AES256_GCM,data:00hRGJPxrYBrlbwdP1yvEdTQSDhglJ4+ALFYP4Jm2vx/LELLHiQor1qGwiwHgR1tONthT6jHb+iT0dLvAyseAoKjfHg5qn29VEfP0ufTTj+cmxMNaoVnCP3Ff/4BVJafqxq6JKkA48yfv3PVYAsnArruscEKhqQH8nUvxut2PHg=,iv:gmXp+f2/peo5RsEbysXd30YbgJUiVqPfvR7acd2uWkI=,tag:II8AvGnyFSEnPpdCanPtlw==,type:str]
    shamir_threshold: 3
    version: 3.13.1
