apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZfNS5cpF6JZl2imTJudwRSQwAM9IIGulDPteO4Q1VSTGfqTZfFlfGStKjRFOzW3gf/Es4HyKcdR8iHByZnHUv1sIMcTlMqr/rgCWnwMkHLVuLEJlAwAmd8mzHGmM1luQ3O2njC8zdR7nZ5AMK98nVziPPCGu8AY/dIKx66r49ruJUw3PWSFVU2+QK231bRn9YGBafq5+gOJRVvV+axIVzztwWceB8X67I+CRW75oAiCVA37SlnWjAPuw5112cV3UH3pJ/fuAZQAWwfLX9YzQnkMMvMSUhKLi4HOI58tmOuFpjyyGpm6g4Y/z/4fsAN3/IAl0chb2XtT0X9YAOrF49YmbOMx7XxQAVSSpBDFXNQMsQerhOBv4XrIHuGQO8rWZ,iv:T1csNyscSXsomaUxIkuwZOnzsVOtosXglglLIaMaUYQ=,tag:5MJvAt7kshZxBp3qdddMsQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:C/nBsNC4bNjisfQDYh2VwY7ZXX2M/MCxY4/Wb0Rh0qlaEQ0YbWbJnTDsDryCiMhbgunvtxlj1cqwi694OH5hGoGWON82fO7CexhKagjNdDxpjZIvJY8d/mSghaaw/n35dol+rGsh0Lt5Ve4HT+6o2AWauVwL75L4EwwWhBhqAmiaM+UZ3rzlvi9eqeoRO9W4+syTKKKF1AxAFG1LeSY45hAL/w2Bf2SeEM3iMv+IzesoC6LyOfCbkQ6cIOZSTqOQzkf/hLy+dFt54NvJXg==,iv:4Rs0poAywdEdatuadZiDj3cRr4xs2ptIHqVOssK/+94=,tag:0AiSzoO2aCTBuND2S4Qz3A==,type:str]
    known_hosts: ENC[AES256_GCM,data:RXesTMjunN+xchmTwAtKexi+d2XdPONpzbpJzb133mxV9sGYp3rlJ5AEpEyLjQH3vKbbdEjgkp+JpT+RNjKfykrRVdHO3LFosw6xP31m4HluAwmzdBwSW4TQ6FzKbucK3AfH1DvEXyADFC+7jCMVujwkUELs+YL1NnKDQw7ZzCuEVilrNCSzCVUMXl4ssPShECoamKIuCfY77mDhcksRn+bkaybAl4yResJV,iv:QC7D/cz8EVhL1W9n9pScTo+7rXLnxE1UXh4Wir4mVTs=,tag:vTdR/nVPUViZXQzmm94eXA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWd1J6Z1ZWd3lGNkdRdjZi
            VEttRE1mTklQWE5SMFdEdFRuYUVHdEdGdmpzCitKcS9RdXYxQjBEUk1NVUp0Z0Zk
            cGJGQ0JUeCtOWVU5RDhOeDRFNXVTM1kKLS0tIDB1QWFVZlRJdEt5RmRkaWFtTlJv
            V2J2TG5ZOVIyNml4a1RHdmRseENuYUUKtlLCm2oE5MFeUeAE561Xl//d6nd8bTow
            03Z8eKeGO+ew0BgR0z6LaxGhzr3mrnjCIXrQdDRfYGX1bY9Xq6Zh9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9mu36rp8zc4fy9pexe2mxlu4rk4ef3gg4tts6j0x5svsctdx5yscrk8rx
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-07T10:05:31Z"
    mac: ENC[AES256_GCM,data:3RRY86/Nnmfocl4i4Se9SCQrIG2OmoZaUB6e2+7IKREic5uqdzRHkcGsEc+TSFVF0gzhZFlFrwSk6OzRWPivoFdS+hMrvUc/DMamBfBu2VYBzB8D/HATt5Ed9wUX69ZBxuadTuCPh0QaVlN7B/xYV21xNnm0wEdjXwI6Zav5zyc=,iv:HCEgjoen7ifKeGiMulEVoxf0mLvRK79XDyS53TaK8Rk=,tag:ecHW156GbQPqusnpTCP8yg==,type:str]
    shamir_threshold: 3
    version: 3.13.0
