apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:7H/KmN8PiOy2eC/6KqU4NAjkbD5gh5sEq04WZwKAt2mv1pPl7MrTy3zo8nA7BYI5Y8aQ75PZQ7Fwi2zh3cFm57tezuQc75RzknG7179ntf3tKmo7BpsfoTwM4nqBmws21/Nm2BB9kUF5CVez3Xu2tDG6X0eHvgSVrQ==,iv:WdofMQcVmEDWG4lOW/UCEnXgGUvf97J+HS+mXZvSfh0=,tag:kULltTSPGav7Fdx62zH0xA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUm5lU3lNVGZnNENkc2Vz
            YkJkRmdaTXJxQVY2TlVPRTdsT1VaRzZkMlRrClEzSXpjY3FhZ2FXZ2xlUXdJVFFV
            MEZtOHFYM2R3NS82akNXd1NKSmxpOGsKLS0tIGJ3dGxLZ1laR3kxVGNBN1F6SVFF
            d3M0YlA1S1AzQURCNFB3K0x3NjJ4ZzgKUKn4K6VMhWxzDo1ne3sG8bGgFTiiXcXC
            iKLCtzs/ckwbV2dlPRKnOKQ7APHKB0aKGs55Za9XdBHW9n0KdiKbKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9mu36rp8zc4fy9pexe2mxlu4rk4ef3gg4tts6j0x5svsctdx5yscrk8rx
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-20T13:41:32Z"
    mac: ENC[AES256_GCM,data:FmBhJNTpHqUdzViZuV/Kr7kHzaMZGeabYQGMYN7RF1oXGa1HqUhJ2Wlgq2nu96JYKcu7cG0Po6B2oqP5Msf+3bycocRRi2o6+047YjAbRBUBg0wd5ulnkJzQM/0Z5Ka/mMVkXQCKW9appp0YlqQQBp+2PIfAtRHEYuOZZylqYyA=,iv:E00Y4m6rlHUFfEs+OsiXdAmLg4GVoThB74vsQQoVmqQ=,tag:dbKqhkTIjne2g+jSSSE1lQ==,type:str]
    shamir_threshold: 3
    version: 3.13.1
