apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:vViN7vbxToWlclOsQ/rV1Ni9+kioNGiAZX0YWvpvYH6XPsedgRoyO4W/PlEVlRk2C0Fc+TwQbwfY9p7YXijb7KKFXLJ98FBTHI3VPGseZEtmZRQIPfhPvFvksmQsJJgC22RieR51/QPn3yYeoJafiZ66j+06KYG4rQ==,iv:v5ct+/gYkiF2yGjtHEzhPd/K/KFXc7eqK51YoOw1B5A=,tag:Q5bAszVdG5NcFUNpiwlxIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VDNXZzFtVVloMUE4cGJh
            OEU5WDZNL0VSbWE4dGVpS0pIUDNuUmE0ZkVBClNESVNqSk90WTAxaXl4UDJaRG5o
            VlNmcDREZHhFaWh3RDZSdU9QeHBxblEKLS0tIGF3RHlidXBlL25yaXFjUjJDeFFa
            LytEUGE3aXo2bjJpYXpaYlY5OWNWMEkKzmkDV2VQXb3CDe0d3jgx2IjV1ixrFryg
            a0ppxHw8rq5D7r/+ZXKpHCmnQtobgrIXU3r7jB/dRQN+7q6YGDskcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9mu36rp8zc4fy9pexe2mxlu4rk4ef3gg4tts6j0x5svsctdx5yscrk8rx
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-03T09:34:29Z"
    mac: ENC[AES256_GCM,data:0AEtw98bRdWqjTIrBlGRSbQ87udUyv2L6xUVfJw72BeskQn+AwquSwNCuGQJfHLK+JuJ8UExlQqEPi0tWAwoTFsbimHF43DhPDDwuytvxDZAXCNm5qsm1vyNO4gEOqGvWrw6by2iLizPQwqsN5W0stPokl8K4oOYokv5OZ4BS6c=,iv:CSMG4M6+8jtTGO/ReofYTQ5Y1Bir/pFPp6g0731rTXw=,tag:JHc+l7TJ70jWSfzvUD+1Aw==,type:str]
    version: 3.13.0
