apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:w/N6/I46rIjtQ5A5OGco2QFiprw5I17LTwvyYo8jbDT2ooEGUm1z61sVUhp1unGMezs0I7IwSQGAtI1BDw0SWLtQ66FxRghiz4PH+OZCLRLXYrDAaD1SAMc3trenvQhMrRhvK51HgwwqJ+zmWtQCyAHJHr0yIL6TNg==,iv:YXEnS0fP/qLhgtCWNtuBg415DGc5hbx71JvcendMvcU=,tag:q+OHJ+exmDsKJNjw9vfX2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MjhUOW5xQkt5VnNQdUVK
            aWdVWEV1NzVUWU5KcFJ0ejB5UU4vRzFWV0JNCkw5dGh4eE04MW1EKzNkYjZiYVla
            aEJrMVhtUUdrdHVWM1F3NDNTQzRwWGMKLS0tIEo5WmNVRFd2MkFNWUI4YmZxNWVh
            TmVZZFNQSHZnRllhUkNRSVNwVEdUMncKGT3UDu8p+cbPKFjF/LIEsZ1MH5sW5hkT
            HMjiZOAi7ZYy3jZWyQGucHeRmfwrUxHOdm4cEm3caxZXXvbbTbQADg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9mu36rp8zc4fy9pexe2mxlu4rk4ef3gg4tts6j0x5svsctdx5yscrk8rx
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-16T01:46:37Z"
    mac: ENC[AES256_GCM,data:UHu3pGIlsAhUIdMyi6/UinwscULqjqqb+XLuv5lEnWwCwjwNL6vHVnrZvKJcQ2joE0y56imUl1kurb5LAUP3PenHXNwgwbLvG8FgT3kF6RwKxFjfA7LzgzIbEe/e49TFad8lSzqQTsXsxl2959XeM6lzvWFuPxk2/nMixZCZlis=,iv:k+RWpl3MET7jwGmdTo/N3sBQIUV+IXKnPLLHuMTIZG8=,tag:9xHpIb/ID/4XGA8jTY45wQ==,type:str]
    shamir_threshold: 3
    version: 3.13.0
