---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: node-exporter-seb
  namespace: kube-prometheus-stack
spec:
  staticConfigs:
    - targets:
        - ${SEB_IP}:9100
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: instance
      replacement: node-seb
    - action: replace
      targetLabel: job
      replacement: node-exporter
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: doco-cd-seb
  namespace: kube-prometheus-stack
spec:
  staticConfigs:
    - targets:
        - ${SEB_IP}:9120
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: instance
      replacement: doco-cd-seb
    - action: replace
      targetLabel: job
      replacement: doco-cd-seb

---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: doco-cd-nas
  namespace: kube-prometheus-stack
spec:
  staticConfigs:
    - targets:
        - ${SCALE_IP}:9120
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: instance
      replacement: doco-cd-nas
    - action: replace
      targetLabel: job
      replacement: doco-cd-nas
