---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: magicmirror
  namespace: magicmirror
spec:
  interval: 30m
  timeout: 25m
  maxHistory: 3
  # enabled | warn
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: app-template
      version: 18.14.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    credentials:
      cf-restic:
        bucket: "${CF_S3_RESTIC_BUCKET}-magicmirror"
      rfs-restic:
        bucket: "${RUSTFS_S3_RESTIC_BUCKET}-magicmirror"
    image:
      repository: karsten13/magicmirror
      pullPolicy: IfNotPresent
      tag: alpine-v2.37.0@sha256:8deb9a5c9c30608c4abcfc350c0a7964224227653985e883c9207e783971161e
    mmpmImage:
      repository: karsten13/mmpm
      pullPolicy: IfNotPresent
      tag: 4.6.4@sha256:a6a15505e9c90287c7a41abb990779e7ff8b215589abf40772c2d1dcd41f2b5e
    securityContext:
      container:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        readOnlyRootFilesystem: false
    service:
      main:
        type: ClusterIP
        ports:
          main:
            port: 8080
      backend:
        enabled: true
        type: ClusterIP
        ports:
          backend1:
            enabled: true
            port: 7890
          backend2:
            enabled: true
            port: 7891
          backend3:
            enabled: true
            port: 6789
          backend4:
            enabled: true
            port: 8907
    magicmirror:
      mmpm: []
      modules:
        - module: clock
          position: fullscreen_above
          config: {}

    configmap:
      mmpm-env:
        enabled: true
        data:
          mmpm-env.json: |
            {
            "MMPM_MAGICMIRROR_ROOT": "/opt/magic_mirror",
            "MMPM_MAGICMIRROR_URI": "http://0.0.0.0:{{ .Values.service.main.ports.main.port }}",
            "MMPM_MAGICMIRROR_PM2_PROCESS_NAME": "",
            "MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE": "",
            "MMPM_IS_DOCKER_IMAGE": true
            }
      mm-config:
        enabled: true
        data:
          config.js: |
            {
            let config = {
              modules: {{ .Values.magicmirror.modules | toJson }}
            };

            /*************** DO NOT EDIT THE LINE BELOW ***************/
            if (typeof module !== "undefined") {module.exports = config;}

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                NODE_ENV: production
                MM_PORT: "{{ .Values.service.main.ports.main.port }}"
                MM_SCENARIO: "server"
            mmpm:
              enabled: true
              imageSelector: mmpmImage
              probes:
                liveness:
                  enabled: true
                  type: http
                  path: /
                  port: "{{ .Values.service.backend.ports.backend1.port }}"
                readiness:
                  enabled: true
                  type: http
                  path: /
                  port: "{{ .Values.service.backend.ports.backend1.port }}"
                startup:
                  enabled: true
                  type: http
                  path: /
                  port: "{{ .Values.service.backend.ports.backend1.port }}"
    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        hosts:
          - host: server.mm.${DOMAIN_2}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: general-le-prod
      mmpm:
        enabled: true
        ingressClassName: internal
        targetSelector:
          backend: backend1
        hosts:
          - host: pkgmanager.mm.${DOMAIN_2}
        integrations:
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: general-le-prod    
    persistence:
      mmpm-config:
        enabled: true
        mountPath: "/home/node/.config/mmpm"
        targetSelectAll: true
        volsync:
          - name: mmpmconfig
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      mmpm-env:
        enabled: true
        type: configmap
        mountPath: /home/node/.config/mmpm/mmpm-env.json
        objectName: mmpm-env
        subPath: mmpm-env.json
        readOnly: true
        targetSelectAll: true
      config:
        enabled: true
        mountPath: "/opt/magic_mirror/config"
        targetSelectAll: true
        volsync:
          - name: config
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      mm-config:
        enabled: true
        type: configmap
        mountPath: /opt/magic_mirror/config/config.js
        objectName: mm-config
        subPath: config.js
        readOnly: true
        targetSelectAll: true
      modules:
        enabled: true
        mountPath: "/opt/magic_mirror/modules"
        targetSelectAll: true
        volsync:
          - name: modules
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      css:
        enabled: true
        mountPath: "/opt/magic_mirror/css"
        targetSelectAll: true
        volsync:
          - name: css
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
