apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - plex/ks.yaml
  - books
  - fileflows/ks.yaml
  - fileflows-external-node/ks.yaml
  - posterr/ks.yaml
  - tautulli/ks.yaml
  - pasta/ks.yaml
  - plex-auto-languages/ks.yaml
  - managers
  - downloaders
  - indexers
  - requests
  - tauticord/ks.yaml
  - calendarr/ks.yaml
  - utilities
  ## - muse/ks.yaml
  ## - checkrr/ks.yaml
