apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - plex/ks.yaml
  - fileflows/ks.yaml
  - fileflows-external-node/ks.yaml
  - posterr/ks.yaml
  - tautulli/ks.yaml
  - pasta/ks.yaml
  - plex-auto-languages/ks.yaml
  - tauticord/ks.yaml
  # - muse/ks.yaml
  # - checkrr/ks.yaml
  - calendarr/ks.yaml
  # - sonobarr/ks.yaml
  - utilities
  - indexers
  - managers
  - requests
  - books
  - downloaders
