creation_rules:
  - path_regex: .+\.enc\.env$
    age: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan
    format: dotenv

  - path_regex: .+\.enc\.txt$
    age: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan