x-healthcheck: &healthcheck
  test: ["CMD", "/dozzle", "healthcheck"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  dozzle:
    scale: 1
    image: amir20/dozzle:v10.7.5@sha256:0ecac18a3491962002e9d6b9f9a363155131a4213e723ab86fc76dfee6e3cd8e
    container_name: dozzle
    restart: on-failure
    environment:
      DOZZLE_ADDR: :8080
      DOZZLE_ENABLE_ACTIONS: true
      DOZZLE_ENABLE_SHELL: true
      DOZZLE_NO_ANALYTICS: true
    networks:
      - network_internal
    expose:
      - "8080"
    healthcheck: *healthcheck
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: true
      traefik.http.routers.dozzle.rule: Host(`dozzle.${BASE_DOMAIN_0}`)
      traefik.http.services.dozzle.loadbalancer.server.port: 8080
      traefik.http.routers.dozzle.entrypoints: websecure
      traefik.http.routers.dozzle.tls: true
      traefik.http.routers.dozzle.tls.certResolver: cf
      traefik.http.routers.dozzle.middlewares: error-pages-middleware
networks:
  network_internal:
    external: true
  internal:
    driver: bridge
