x-healthcheck: &healthcheck
  test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/healthcheck"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  homepage:
    scale: 1
    image: ghcr.io/gethomepage/homepage:v1.13.2@sha256:a0b71c8e757298d02560186bab9fbe3fc2d375c523a62cc1019177b37e48aa28
    container_name: homepage
    restart: on-failure
    networks:
      - network_internal
    expose:
      - "3000"
    healthcheck: *healthcheck
    env_file:
      - ./hp.enc.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${BASE_DOCKER_DATA_DIR}/homepage/config:/app/config
      - ${BASE_HOME_OPS_DIR_APPS_OBSERV}/homepage/configs/bookmarks.yaml:/app/config/bookmarks.yaml:ro
      - ${BASE_HOME_OPS_DIR_APPS_OBSERV}/homepage/configs/services.yaml:/app/config/services.yaml:ro
    labels:
      traefik.enable: true
      traefik.http.routers.homepage.rule: Host(`homepage.${BASE_DOMAIN_0}`)
      traefik.http.services.homepage.loadbalancer.server.port: 3000
      traefik.http.routers.homepage.entrypoints: websecure
      traefik.http.routers.homepage.tls: true
      traefik.http.routers.homepage.tls.certResolver: cf
      traefik.http.routers.homepage.middlewares: error-pages-middleware
      wud.tag.include: ^\d+\.\d+\.\d+$
networks:
  network_internal:
    external: true
  internal:
    driver: bridge
