apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pkvault
  namespace: pkvault
spec:
  interval: 30m
  timeout: 25m
  maxHistory: 3
  # enabled | warn
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: app-template
      version: 18.23.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    gatus:
      group: games-utilities
    credentials:
      cf-restic:
        bucket: "${CF_S3_RESTIC_BUCKET}-pkvault"
      rfs-restic:
        bucket: "${CF_S3_RESTIC_BUCKET}-pkvault"
    image:
      repository: ghcr.io/chnapy/pkvault
      pullPolicy: IfNotPresent
      tag: 2.3.4@sha256:49cffcb01fa12e25819ab5b948f8a7e5de28952bb710e66887ea5f29b728389b
    securityContext:
      container:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        readOnlyRootFilesystem: false
    service:
      main:
        type: ClusterIP
        ports:
          main:
            port: 3000
    # workload:
    #   main:
    #     podSpec:
    #       containers:
    #         main:
    #           env:
    #             TEST: 1
    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        hosts:
          - host: pkvault.${DOMAIN_2}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: general-le-prod
    persistence:
      config:
        enabled: true
        mountPath: /pkvault
        volsync:
          - name: config
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      saves:
        enabled: true
        mountPath: /pkvault/saves
        volsync:
          - name: saves
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
