x-healthcheck: &healthcheck
  test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/healthcheck"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  homepage:
    scale: 1
    image: ghcr.io/gethomepage/homepage:v1.13.1@sha256:d8d784e5090111b6e4c56dfd90e272d2953a2094e87349f647165df0fa6c4401
    container_name: homepage
    restart: on-failure
    networks:
      - network_internal
    ports:
      - 3000
    healthcheck: *healthcheck
    env_file:
      - ./hp.enc.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/xstar97/docker/data/homepage/config:/app/config
      - ${BASE_HOME_OPS_DIR}/apps/system/homepage/configs/bookmarks.yaml:/app/config/bookmarks.yaml:ro
      - ${BASE_HOME_OPS_DIR}/apps/system/homepage/configs/services.yaml:/app/config/services.yaml:ro
    labels:
      traefik.enable: true
      traefik.http.routers.homepage.rule: Host(`homepage.${BASE_DOMAIN_0}`)
      traefik.http.services.homepage.loadbalancer.server.port: 3000
      traefik.http.routers.homepage.entrypoints: websecure
      traefik.http.routers.homepage.tls: true
      traefik.http.routers.homepage.tls.certResolver: cf
      traefik.http.routers.homepage.middlewares: error-pages-middleware
      homepage.tag.include: ^\d+\.\d+\.\d+$
networks:
  network_internal:
    external: true
  internal:
    driver: bridge
