x-healthcheck: &healthcheck
  test: ["CMD-SHELL","wget -q --spider http://localhost:2376/_hawser/health || exit 1"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  hawser:
    scale: 1
    image: ghcr.io/finsys/hawser:0.2.47@sha256:ca7e7a729f64fc1ed87300b3a0c08d23a5d4ab12e73e846f375dc416dd9556af
    container_name: hawser
    restart: on-failure
    env_file:
      - hawser.enc.env
    environment:
      STACKS_DIR: "/opt/hawser-stacks"
    networks:
      - network_internal
    ports:
      - 2376:2376
    healthcheck: *healthcheck
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - hawser_data:/opt/hawser-stacks
networks:
  network_internal:
    external: true
  internal:
    driver: bridge
volumes:
  hawser_data: {}