---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: medialyze
  namespace: medialyze
spec:
  interval: 30m
  timeout: 25m
  maxHistory: 3
  driftDetection:
    mode: warn
  chart:
    spec:
      chart: app-template
      version: 18.7.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gatus:
      group: media-utilities
    global:
      stopAll: false
    credentials:
      cf-restic:
        bucket: "${CF_S3_RESTIC_BUCKET}-medialyze"
      rfs-restic:
        bucket: "${RUSTFS_S3_RESTIC_BUCKET}-medialyze"
    image:
      repository: ghcr.io/frederikemmer/medialyze
      pullPolicy: IfNotPresent
      tag: 0.15.0@sha256:0a01335a7ddc3a88f1d85a58e83531613f98a06f20ebfd7d7b8993cc1639c47d

    securityContext:
      container:
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        runAsUser: 0
        runAsGroup: 0
    service:
      main:
        ports:
          main:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        hosts:
          - host: medialyze.${DOMAIN_2}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: general-le-prod
    persistence:
      config:
        enabled: true
        mountPath: /config
        volsync:
          - name: config
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      media:
        enabled: true
        type: nfs
        server: ${SCALE_IP}
        path: ${MEDIA_NFS}
        mountPath: "${MEDIA_LOCAL}"
    cnpg:
      main:
        enabled: false
