x-healthcheck: &healthcheck
  test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:9999/ || exit 1"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  gluetun:
    image: qmcgaw/gluetun:v3.41.3
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - internal
      - network_internal
    # healthcheck: *healthcheck
    env_file:
      - ./gluetun.enc.env
    environment:
      TZ: America/New_York
      VPN_SERVICE_PROVIDER: custom
      VPN_TYPE: wireguard

networks:
  network_internal:
    external: true
  internal:
    driver: bridge
