apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - namespace.yaml
  - server.yaml
  - peers
components:
  - ../../../../components/notifications/discord
