x-healthcheck: &healthcheck
  test: ["CMD-SHELL", "curl -fs -o /dev/null http://localhost:8000/status"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  apprise:
    image: caronc/apprise:2.0.1@sha256:0b2913b15c8eb47c25345722985ffbfae701326edde21909c205d296d62dd52c
    container_name: apprise
    restart: unless-stopped
    networks:
      - internal
      - network_internal
    expose:
      - "8000"
    healthcheck: *healthcheck
    environment:
      TZ: America/New_York
      APPRISE_WORKER_COUNT: 1
      APPRISE_STATEFUL_MODE: simple
      # APPRISE_ADMIN: "y"
    volumes:
      - ${DOCKER_DATA_DIR}/apprise/config:/config
      - ${DOCKER_DATA_DIR}/apprise/attach:/attac
    labels:
      traefik.enable: "true"
      traefik.http.routers.apprise.rule: Host(`apprise.nas.local`)
      traefik.http.routers.apprise.entrypoints: web
      traefik.http.routers.apprise.service: apprise
      traefik.http.services.apprise.loadbalancer.server.port: "8000"
      traefik.http.services.apprise.loadbalancer.server.scheme: http
networks:
  network_internal:
    external: true
  internal:
    driver: bridge
