x-healthcheck: &healthcheck
  test: ["CMD-SHELL", "curl -fs -o /dev/null http://localhost:8000/status"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  apprise:
    image: caronc/apprise:v2.0.0@sha256:cc5ef662ad2a4a25958f1eddbf87f2e95f9bf637ea481f1adcec18312ad262f5
    container_name: apprise
    restart: unless-stopped
    networks:
      - internal
      - network_internal
    expose:
      - "8000"
    healthcheck: *healthcheck
    environment:
      TZ: America/New_York
      APPRISE_WORKER_COUNT: 1
      APPRISE_STATEFUL_MODE: simple
      # APPRISE_ADMIN: "y"
    volumes:
      - ${DOCKER_DATA_DIR}/apprise/config:/config
      - ${DOCKER_DATA_DIR}/apprise/attach:/attach
networks:
  network_internal:
    external: true
  internal:
    driver: bridge
