---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 30m
  timeout: 25m
  maxHistory: 3
  driftDetection:
    mode: warn
  chart:
    spec:
      chart: authentik
      version: 40.8.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gatus:
      group: auth
    global:
      stopAll: false
      skipEmptyWalArchiveCheck: true
    credentials:
      cf-restic:
        bucket: "${CF_S3_RESTIC_BUCKET}-authentik"
      rfs-restic:
        bucket: "${RUSTFS_S3_RESTIC_BUCKET}-authentik"
    authentik:
      credentials:
        email: ${AUTHENTIK_ADMIN_EMAIL}
        password: ${AUTHENTIK_ADMIN_PASSWORD}
      # outposts:
      #   proxy:
      #     enabled: true
      #     token: "${AUTHENTIK_TOKEN_KEY}"
    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - host: "{{ .Release.Name }}.${DOMAIN_2}"
            paths:
              - path: /
                pathType: Prefix
          - host: "*.${DOMAIN_2}"
            paths:
              - path: /outpost.goauthentik.io
                pathType: ImplementationSpecific
        integrations:
          certManager:
            enabled: true
            certificateIssuer: general-le-prod
    cnpg:
      main:
        mode: recovery
        cluster:
          singleNode: true
        backups:
          enabled: true
          credentials: cf-restic
          retentionPolicy: "7d"
          scheduledBackups:
            - name: daily-backup
              # https://crontab.guru/#10_0_*_*_*
              schedule: "10 0 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false
        recovery:
          method: object_store
          credentials: cf-restic
    metrics:
      # FIXME: Metrics do not work yet
      servermetrics:
        enabled: false
