apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: kube-prometheus-stack
type: Opaque
stringData:
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:RRZIncA5aeFDnkUFV3BtQrMcLHZpz4Pg3MBAXlIjEGwdxW4fxm9oxpBySGh7JBMqnU8SAbdZjyKWyOWKk0vcrQ/ETvzuT57lLqMhFliG7G/I8EYNc1RWXOUNmgVe66P81QKoSXJXIOYZ6c6s4vIFY7GNxTlrJsYUog==,iv:bsBbcH1/DygZzRz0/isEE/3EAX0/ll6VZK87UJYW9wQ=,tag:EkGIoZbcCghLEGWdxOhipQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycWIrWjJHWEVldUljOVov
        Q2t0Sk9lbkhqS0cycnI1cFZ3RWVtQmNQN1hzCllIRTZMY1NKY2RibEo1RkcwSHpG
        dnluN3p0ekVHWVhDM2d4SmlwbEd4dHMKLS0tIExmdC9hUU1zMTcrbFJNM202UTJF
        NElUZHBPSi9KenVlSzI0U0RCWEhUSWcKu9OGMZ5TiBYlJ/qBp9SbZ/Jc+HKqM0Ul
        Eatn17eKg2ZPS7UXbwK1UMnd6HVpIOj34uxKKZshcfF+NQtCUsQL9Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T13:40:09Z"
  mac: ENC[AES256_GCM,data:PvJSSA+xq1rmWyT5Xf6gKUpS5cZNw+XZ9gyZxsC01z2uqhI1nOPztzu/zngeJjLqHBqdgEub3mtWblaD21zcSqgNf0N/zWJ8dIvB8aI8mHr8z8y18+ljOnfxwOtkrG7X5cP+RDAF2h6G3Z9T66y7KCz460cEHDIjeIkdTE4H5JU=,iv:o6g8rHbT6VJKxtBuhWPdHUla9jyjodBrMTDthdnzJrg=,tag:BSPjqc/RsgKToHmYB6UIrA==,type:str]
  mac_only_encrypted: true
  shamir_threshold: 3
  version: 3.13.3
