apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: kube-prometheus-stack
type: Opaque
stringData:
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:cYiLBUCcUeMLa1VVXmGbTZjXj4aaT4Lo4zmXMZIkCotVCMums99RldNfio6U/Tq4Mzz/7kSNoTSi12KN3CxKdThiBrOIQLn0HwSPKEFVougbrHgeEZWzhHIgEAEaViBUlAwdqkAdbGD0bhEHaiLp4l0U8C4qJop7zA==,iv:/5fJ5F4fAhtXz7A0RhkSGZvuBNUPLlWEFqdmfiAwPbU=,tag:vSynr9yffVbFhYczwW1pkg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudW9rRmJzd3FrSjd1US9w
        YUg2RnZKaDVudzV6QmMwVkJRZTZHVXNDd1Q4CnlmM3h6aElteE9vbGk2eWE1S0pS
        eml6K3VTVGJKTFp2ZXBUcno5VS9GaXcKLS0tIEtNUmlMOENVc016bitFNy95d3do
        cFpHZE5vZnUvVnJxVGkwTm1qS0JVTHMKzroZQlhwjCIJ9CrvJs6hsf0Uyh2xxJ7R
        VmFGipWgFDPHHlweFij+ZZboOHyFwJT4Gy/KjCr3Dm2uUlNVPkFZEQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T08:21:11Z"
  mac: ENC[AES256_GCM,data:+EmgxDLV1BtjU2ED87vMxweSg1wxRwW4GWPdHL1e4X1owGRK04DROhEofpD7olVWRE60hBi01cNpt4Nbn0jtqZbsb92lNTjfd/uiNrfJM+3oIEx7gJA1mcvVIkgJeRXc+BM8CtzBvc3iSreP5vArr+IKQ6ukMnZemv5un7e+7l0=,iv:6ii98IvcA2KqBJyvTvLnIUIMydMLqJT0paMS+hNmQnE=,tag:3wuWz85a4a+OAuWgx8CTiQ==,type:str]
  mac_only_encrypted: true
  shamir_threshold: 3
  version: 3.13.3
