apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: kube-prometheus-stack
type: Opaque
stringData:
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:XOvGbUgDUWAZXCW8u6JxBVTqsWT9KApyKtWIoYDU4TlepjQD32HtIkcER/ovVHQaCZcqQdjvRqfM6cJabCpgJAaArUtJm6C6mimUFjMIqwBwhjmpckOkD7MEeeBKCl6iuTHyAh/Lzs0PlwurUGdIRrA61o+sLfP4XQ==,iv:TmnHwur/CWz6NIbpwuyC0E5ZDRtwAWT5HYG8CbN9ZTE=,tag:unJp7lDzn6mm4rQ2XZ/L2g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOTIvMCtRVDl6cFdvQlln
        MmVkcUQyMEh4bERmWjRaaWhrdWNkbVkvaXcwCkhhcUFHeHc1a1RuZWdaNmJ2V25E
        MEdkcTJBTWFQN1Zmb1VLWXV6cVVrQkEKLS0tIElubm85Y3R1VWdPUVBudC81dFha
        R3psNWtzZnowbXNvcVVoR0lHbXJTdmsKiN0Z7Xhz006Sl+pXlAYGmRptAMs9kWpO
        vsy3ETGPBC3OdS2hgxSlaZr1XQFnKuSc++ZuIEQW15SqevOEbVPhqg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T13:39:49Z"
  mac: ENC[AES256_GCM,data:Q+jHrfF7MIcsjCyEAKDPsQIEy3ZxnsaQ+yHRpGO/0OGv8moUmW0UKBf3kFY5y+oYZ9AICC6Ipgh9SEmXGMpebQmJKCl4iSLW6qlT7BGSqzcxwGdogGQdTAE13n2aWeH/mwEmcIw5d4h9N6QoL48Qy/0vOtS0Hh6bjX9ftCT3pF8=,iv:o/p975YnVDcT+ly+Row7mtK0T+oR0nvZ+cI5slu+jA8=,tag:PRLBE9ABx43wfou3AVXIqw==,type:str]
  mac_only_encrypted: true
  shamir_threshold: 3
  version: 3.13.3
