apiVersion: v1
kind: Secret
metadata:
    name: prometheus-wireguard
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:gBFj1eq08Chd5pN7ofGM7A9/Kcy0ilzvZ7AAjiBLYY8W3yD5t/4uUogt60U=,iv:wexJeOtxnA59v/6mviXOlgIhJdj2uPNB96uQqEO3xzY=,tag:cLMSAnkjKu77P2XPo5sKCg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:nLgNU1KmlnMPFj8=,iv:fFjyH1gwIUv25b21KoBOxqndr/aezIpHJHad67T80zk=,tag:HRvQpXnjZKZSeTmpSiDEGw==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:Hdk6rKKCuzgPFnle0IyhQMILT5/luFYzunEPNhc0Vwbc1gB1cb6yQNxRh2A=,iv:9mKo2GP2tHPazMee0XmeU16puhWnxlskbzdC0xOAfqQ=,tag:LGgbmXlpD1BzzovCH2f9Gg==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:h/bADCjRVA/n0g==,iv:ObDbxcQ3H6yBRwlDBwG1ZLyY/U9jukSbEvT82fufhso=,tag:EPMcI0uRBoi8oxrLKPGnTQ==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:YWxec4A=,iv:A/yXrWJhYcFa5tYP4uI7icewQdWx6+d6/8UE8g8q+zU=,tag:6YAJPmtCB3Q6rZAMTLqkrQ==,type:str]
    WIREGUARD_ALLOWED_IPS: ENC[AES256_GCM,data:D46TwCdcGV35,iv:Ir6DbUuWoducHKvR9o+On1mJ24XCAYVW8eOvOG4lpec=,tag:vlYlUkVx7932BDl5BC5nbg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZmJXSm1PYjlrVEVBQm9Q
            SUtJeFI5aUxkS1ErcFdQU2lzNmlqZXZySVM0CmU1WXRMempFNGFlNjdoQStRZU4x
            cmdVSTk5Q212WUxQOTVaU0tVUzRFTWsKLS0tIHVSVE5DWnRwaWNmWGQySTd3TGkr
            SUdlcHFwUWNGRm9lK0dQcG5OL0tCUFkKvWr9oqLafJRr1yNAfAsRlAgUzhpISRpA
            ImUzoLofW3r9BJzIxSFa7CBxTK2upPjz/Uw1hL0D6Cvv3+68oIVYMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T11:47:04Z"
    mac: ENC[AES256_GCM,data:rVAmIdlBxbR3ZL2zLNxXwU/gaMvzSSZCRE3eADPhgWuJH/uQn7+uDDUI6z0k2EZ7Kb8dZMemjd6l1WrsIp4MBz5IsXvLNK3XzrEeUP3s+rESxQlFE+KFhlzBUp9IZ2MKtz6E8ntaMxZccEEUC+1hLo15aOo0eZWE17exzyf3a/0=,iv:BOf/4MzCDyKfEe0pyUbv5dFRF9JnjQ01GmXUsL96W2w=,tag:v6EMzQpOY1DlyiB1J7M8Yw==,type:str]
    mac_only_encrypted: true
    shamir_threshold: 3
    version: 3.13.3
