apiVersion: v1
kind: Secret
metadata:
    name: prometheus-wireguard
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    VPN_TYPE: ENC[AES256_GCM,data:qmgtxtjuDaYP,iv:M+43HNMebf6WnHKKSpx1seS+j7w9abQkdExEJDMenPc=,tag:Qs1ToLhvcvxcLXO9UUXGRg==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:5w2C4h87,iv:3Q9lt4cm9KjAapQVBBwxSyNvHDEAQJ8qjx5o/AS2swc=,tag:Iw/PwgqYplQI3Y9Lhbbcfw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:gBFj1eq08Chd5pN7ofGM7A9/Kcy0ilzvZ7AAjiBLYY8W3yD5t/4uUogt60U=,iv:wexJeOtxnA59v/6mviXOlgIhJdj2uPNB96uQqEO3xzY=,tag:cLMSAnkjKu77P2XPo5sKCg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:nLgNU1KmlnMPFj8=,iv:fFjyH1gwIUv25b21KoBOxqndr/aezIpHJHad67T80zk=,tag:HRvQpXnjZKZSeTmpSiDEGw==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:Hdk6rKKCuzgPFnle0IyhQMILT5/luFYzunEPNhc0Vwbc1gB1cb6yQNxRh2A=,iv:9mKo2GP2tHPazMee0XmeU16puhWnxlskbzdC0xOAfqQ=,tag:LGgbmXlpD1BzzovCH2f9Gg==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:85n7gTTR7781DCsegdNjX/LHLmrrtz1dbx9uA/KOtBFdNplKxmGtUc89T2JWbg==,iv:tglurT7Bk0d1lX3zoFqS48DyAZLIr89zpiiiTT5MExE=,tag:yAfJmVrQC6qwIRXeA7eRxg==,type:str] #ENC[AES256_GCM,data:jOH2dOJUFNqqM6s=,iv:ZuM5lMV/c2olWltV9xOJH8hSMHaAJnI/gr73J/il6Hs=,tag:Vw5G04Tdcbu2fIL5oPc3gg==,type:comment]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:YWxec4A=,iv:A/yXrWJhYcFa5tYP4uI7icewQdWx6+d6/8UE8g8q+zU=,tag:6YAJPmtCB3Q6rZAMTLqkrQ==,type:str]
    WIREGUARD_ALLOWED_IPS: ENC[AES256_GCM,data:DyFcq+Tdp/qtMMdCx2vwfSxdO7SSzftqnyLJIdCz/hYUgCPmCN/Gk8NPPKuktzeCJSbr7Lvs9SSWIeUVDBsEWulR,iv:ooQGcu0SO/PbuS06tqk8SKntF+WeWHzR2mEgKRRPvRU=,tag:dgiEBvrf48PHC/PTTm4Y1A==,type:str]
    WIREGUARD_MTU: ENC[AES256_GCM,data:/6XDBg==,iv:/rYhRqXY80u7Vx6QU2S0YvzGJW48FB+vQ109W8Y3fiA=,tag:AICLEhwFAoe6GICcUXvUug==,type:str]
    HEALTH_VPN_DURATION_INITIAL: ENC[AES256_GCM,data:KVSP,iv:D3wnzLMw9GTWQLO0N6Puoc0D6xGurjQgCalPRUB415I=,tag:MF8q9HtwHReoK/32w184qA==,type:str]
    HEALTH_VPN_DURATION_ADDITION: ENC[AES256_GCM,data:xtqY,iv:84avIl1ijVu9FPhxiKqeaCF4OLBv4LKXghQnuSBV5t0=,tag:ub/JLxBuBi+E2PqGpLIhmw==,type:str]
    HEALTH_VPN_INTERVAL: ENC[AES256_GCM,data:lWCr,iv:+CD4lUfR3QWfYUGgpkYCO2KEmKVraS41NVBFWqz7EmE=,tag:4G+qw8lbO3mfv5RxMtlOVA==,type:str]
    HEALTH_VPN_RESTART_VPN: ENC[AES256_GCM,data:xtk=,iv:Wx+D21YiAP9773ZstRNXUDCZtL2qJgUQmpdZsuQJmPg=,tag:a4JtsjygskjhDfvWmfpXTQ==,type:str]
    DNS_UPSTREAM_RESOLVER_TYPE: ENC[AES256_GCM,data:L/Tmp8k=,iv:eEzuTtlCESOdoAMYaZcP7raDbJL+Pea5GlSSvCf9HWw=,tag:vhgAhe6he9QqGVfzvEpG8w==,type:str]
    DNS_ADDRESS: ENC[AES256_GCM,data:t1kXmk1QaDE=,iv:8L6yMJZJw2+D41sSqgDKRzQPTeoEKx8QqlrG7TxD9Ng=,tag:WYlXm14flNm1FQmtfoPtQg==,type:str] #ENC[AES256_GCM,data:knvTVc3eLMb51b7eSg==,iv:CfxYftivZ3uVLgd1CamouV1tzbuu4KZXkQWjr25kViI=,tag:dr6vRyQ5YacQfjk6Itw8cw==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZmJXSm1PYjlrVEVBQm9Q
            SUtJeFI5aUxkS1ErcFdQU2lzNmlqZXZySVM0CmU1WXRMempFNGFlNjdoQStRZU4x
            cmdVSTk5Q212WUxQOTVaU0tVUzRFTWsKLS0tIHVSVE5DWnRwaWNmWGQySTd3TGkr
            SUdlcHFwUWNGRm9lK0dQcG5OL0tCUFkKvWr9oqLafJRr1yNAfAsRlAgUzhpISRpA
            ImUzoLofW3r9BJzIxSFa7CBxTK2upPjz/Uw1hL0D6Cvv3+68oIVYMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T12:41:43Z"
    mac: ENC[AES256_GCM,data:2ohPXFEFNGSRzG19j4Q5Insb0fGRlYKkuKQHwSOgMq5tz/6x05YaUlgM/l3J0vl4TFbORVzKCNA+LsZHK6rwkMOEGoGgU5mjq1SVrAKgDZUHIU4hhl9m0e5pWB5RpSWj9/GzydkGZOWMdOWGzD08t+tB/0spLCSPGSQIaDb5wSA=,iv:lRZu1EzkyGFhshtD5GGEVgM6N8rXlbqj4zTtU4xeaYI=,tag:WRv0/5R3w3SM5rpyqed2Nw==,type:str]
    mac_only_encrypted: true
    shamir_threshold: 3
    version: 3.13.3
