apiVersion: v1
kind: Secret
metadata:
  name: deploy-key
  namespace: flux-system
stringData:
  identity: ENC[AES256_GCM,data:nOPqQ8LSHYJOhWPVoXIQRsQDDrxGpo9do+ydLucNySMHvODzqJqp+LA3yH2AkDBznbeNSL4vuuQ2DtKAKGsXQEBuhm93bYaNlihddb01nWvdKcfmzdrEKroJNox5Qyqz8RjzNKS9IYYtAXnEtgIQCc6lpWowHib6fldOsagUk5iuRnFPfQ4GZ6G0622gDAHSiaskENzWyoNd0yOMkSDZtnt9Otl524DXR5Mqn7IJu0O5rWhi6pqXHzXX9b+iDzZUSXhlem0W5T94bmddzGw8lm6AZdnagczAYOL53p9C+E2EWKFgIpvJwVzn1Z1MYMDFqQHIAIULj2KVjZzI8L6FLPgF1H3yGyivNJNe2GEGl7+4ZSH5jzZM1KGmZ5vT5AnB,iv:owCXY4VmfLgE6HOERp+l2+HIfBIeDMub+qgY9FxbTB0=,tag:B0ay6vMw6wCjYBSnwcZ3Qg==,type:str]
  identity.pub: ENC[AES256_GCM,data:seGPtKCGCoBRWKlS7a4LX2saTHwIR0BpB9tGRUuyi/ZB2yJpYYP6jnlwwkMJb1riLCDWSmBLLMZBaZNx9xeo3iPrBkhrFPhrTe4Fp36QhJXKfkSHpIBlH2RHhFtWH5HGWoKeTpAZlZT5GIAwfHt/Q4ybDtcjl5qb+QcCy+ltlUDJNnqpkYMDl9Zqmv+OhYKCwx9MhM/Cdwd6eYSLbB0mIHs8vE3HZ/+mxmLAN/qlgwiFH0v12Rowi+qEawryxVQuqyoM1Au5SuiAatq5Tw==,iv:EJfwJHxBdOW2R5xOq7F4OjIQweggw9Rea8v6MGKWHaE=,tag:8nfl+tSuDzjPxfcuhhwxRA==,type:str]
  known_hosts: ENC[AES256_GCM,data:/vKGkQ5bWp3wIJYy0hNt1+sb2hhRPXeIGRHKnDayWV57/87+55QVVfeMZ3J1AeNE9ZI+kbOI7zpj/AHdiljFEdAzAxerC+1psTTaluDpMfRHBG+nusckBQkQ11oe/i7sQCF+gOoSFf4jXN7m0Ky3RxO9hBz7nNmJFaIrZIGkPvLM2tBz9kP6gwHjOLBORNSHOrPAfqA3jlUt4Mhy3QKL5e0sjTchzFqGezri,iv:3hNdIuCZ3EJr8+r2erh6mZ+tTDu6kQajOK2MMT28xUc=,tag:vpL7ON/Eg1E/Blhn6Hx4hA==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZmt0UFhWK3FKbFZsbDBH
        Y2pTd2N5QmlRNFR6QzQvdUJoRmp2Zzh2cUE4CnFGakJOZDcvd3lEbjh4cmMrSi9z
        QTdwem5mVnRUYWF5aWc0MFFuNTk2MTAKLS0tIDUzb2MwRjkwM2JqTUVEUTUxL0pC
        OGREZXpTa2RwaTNSWlhFMTQ5c2FORFUKXgYVF3cdC8RFi1pH2QdKtXDgKzPqhWc6
        Edk/PdDxym9f9ncBRysoIG9sPtxnzUAwq1y5Yg2wxC/sTVfCZlKAtw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T13:39:49Z"
  mac: ENC[AES256_GCM,data:Gmtx6yd62T4s8yAEQFcHn78YANXZAyOv/4rCtSgspbnjyyanPv5AnUeYqGAGI/Iy4j0yiR1LAYcxzosCFuEOAZ0So7v0LLue00FMEtNXkC/6lNHwnvQ/dSUcwmeC6kiDXnLMt4YwASApDdthb4MqucqvvVZOB0WMhsIjH+qnRQk=,iv:oYRzMNA58WUcL0cR2RbHivgdsHpuSQDEkBEFtS44/6k=,tag:tChe6vZXLH/PC5Rpiy8Tsw==,type:str]
  mac_only_encrypted: true
  shamir_threshold: 3
  version: 3.13.3
