apiVersion: v1
kind: Secret
metadata:
  name: deploy-key
  namespace: flux-system
stringData:
  identity: ENC[AES256_GCM,data:70J+88W+LtufBnLRsm854hLa5cC4mwajWr0U14OLti+FWCkvhR6sF+vWseqbTkk0jMQ9hU2W/vq05hPcjjG1kgK/FsFcPgQTr9/ltb15n/jvjHbE4o1XDaiNK9LfBzn8LX5oqhQHtgYzKD3OlFF2U+cvNMc+urguGxYlFxCSQ6bwThElN4ZWTBPgrHcJFZn4rWtw+XuY2DfdEc2zEsNZAGX0WQBvmA6+zWskB6yh91XTmJGz0Hm3ehqTqISlKuklKFU1pRRwgxAfKWyVVrwOPo/yjTEZuy+ZNHRVrOTQL9r8eQMa9iNwnVE5Bkoi55ReKGX6ATpaWggWQV2PRS9+y9T6qzrNlLDFropUQfQEGG+HBNzFhq4ExBscE0ygzQIJ,iv:bM9tGRiH1dfxBt9Vkp85GtJnmhpBzH5MGUxMVRdKRE8=,tag:JZx/XmfdILnKU568281PUQ==,type:str]
  identity.pub: ENC[AES256_GCM,data:JK0Y66f55HvfkrW4budPaD9+8e4getF5emg9zr+oRr2NMcMClD6j+1XeIhgDnO4pDKd96rKHvS6/goM3yT8F/3h/Wni7nLUkOruKGAkYSEahkH0Rm/3BVHfun7A3z0tGsgnrTMTA7CNjHN6Zz5h3QRw//rjOVZGL2qx9/tYCWo5OJHUIKpJOqpaI02u0GdrT/rOEM+Rw0JK8c3kA3+7V493xnG2nwS3bMnW+1oHXEG9v6MlBlX3hqF+cYqX4xsyGV0mUaFE3/LSXei89oA==,iv:zm+M6esJVQH0z0WUKtgKw4wLdOC31b/uoDpZq4dfkrw=,tag:lHtRRMximix/sBJE7amovw==,type:str]
  known_hosts: ENC[AES256_GCM,data:8RRRqa4aN8QAbVeSX4T8eWOe52FY+kDO+kQl4NeC3SD9pdS1Mj8Q0PVs+9f4meXGhmYilbqWSpfPXOAqCjefSu3Tmyo/Em/haRj79zg9IfgWyAZDoWCE144gFxFdYTjasojqWsVSx13NOZzvh2FG451MP9O1JDo5mPU8nKkRN29wCYJLMR0M4+s66ApO7sHJcAyUPkomVgASrcDXOv31YnQ6J/YrNASEfK4f,iv:/Rv5V93s9C3JMUHTN+d3JauYC7aA5d22/nVTgQzWA2s=,tag:2dobssmTUX1xZczrZ4QHvQ==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdmxramxSMWdzKzVzZHc4
        OUN1cnJ6R0tId3hCWEpQR3Z1T3pjYUpHMGxrCkgzcUtSalpjeEpCbWFESHl5QjM5
        V1ZHYnlEeVF5ZjFIS2RUQlVGMEd5M3MKLS0tIFJhK1kxYWVQWWlCMEs3M3U0MFE1
        Y2t0RFUrZCtqbCtHT1ZCbC9tamkvY28KO5rxzldDgUDvkEm+ecvGKFcS03GOlXBc
        tnZ4PDPYYB/FZfXZmOX/Ev9gHP3EkdR7Zd58XcMoUcNWSNrgEIeUIg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T13:40:09Z"
  mac: ENC[AES256_GCM,data:aItZkjvZJ1DX9KZufJTB3qHtRuUbz2vYQeaULl9/r7ZJSdRqr7vNXZiw9CKuuaRIrS3AzI0n+jkyf45UXAEmt2Bb2iG3K94VQ0L8BIOknDC7V4ok+3iZiqQsrcgyQynpgsv3hU2AmK7yO5j11NXjWGI0xbvHsUDbvghc9X5i9iQ=,iv:L1SRE8H8tEQ1JPNLqKDam4blUn9IO0+1o1YRCA0QebA=,tag:DbMecl5l/gB+PFmS2Fn3NQ==,type:str]
  mac_only_encrypted: true
  shamir_threshold: 3
  version: 3.13.3
