apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
stringData:
  age.agekey: ENC[AES256_GCM,data:voxcc8WJ14GY8O5zj5DNCgDfj7Q0MR22tlkoLhv3bURVXLfuir7M57bK7ZFQZsCrJo5QnWNFRXfH+eLobXzg5Nmt/nLmIXuseE8=,iv:LPpHIepoD9bDvZsRvI08CADVE00pWkkb3y/dGvAujnE=,tag:mo1YA4fBNn3qGeqDi1CbvQ==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRFo1UzRwQkVFWXdjQVl2
        NW1pTnlYWkJtNGRtdGVlMDdBN3l2eHJNMVdJCk4wVi9YMXcvc3I1OG5sdWxSL2Fr
        aGRsaXRBQjA2ZEF2VGpSaFoxMDIrUmsKLS0tIFcvUCtOeG9yYkxHd0tQK0J6RjZ2
        eFNKNk85dGpld3EyYlBFTkdwWGluUGsKJstnZY9uSorRNArOu1XgY+WCQOQ7jPkt
        RPM5kzVowo32TQk0sClPTQG/2QAvCEYiBaOvIKORQSRwLSi4WSoU2g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T03:24:43Z"
  mac: ENC[AES256_GCM,data:PI/Mt5NW99rBTfdwCnQNtwIfAz5+2fTU1g0htxZzeQfojMl2Efkcpmn2Ie4MmQiUIDfDnsaDSWgjlzZ6uHLZ6KoEK+uezxUyum/K+l1UBoKIPzAkid7DTu6gOUvyGCHw1lZTgSDVVnBKCByxq5ltme5FsDmsOu/xRWv3qftd+fg=,iv:KgZlfPJxsRIjJyBIyeIKpHW7YMw4ObnxKL2g6+4znhU=,tag:IIpTNH3+66niMe9k8UkBCg==,type:str]
  mac_only_encrypted: true
  shamir_threshold: 3
  version: 3.13.3
