---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
  namespace: renovate
spec:
  interval: 30m
  timeout: 25m
  maxHistory: 3
  # enabled | warn
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: renovate
      version: 7.25.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gatus:
      group: core
    global:
      stopAll: true

    configmap:
      config:
        enabled: false

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                GITHUB_COM_TOKEN: '${RENOVATE_GITHUB_COM_TOKEN}'
                RENOVATE_GITHUB_COM_TOKEN: '${RENOVATE_GITHUB_COM_TOKEN}'
                # You can set RENOVATE_AUTODISCOVER to true to run Renovate on all repos you have push access to
                RENOVATE_AUTODISCOVER: 'false'
                RENOVATE_TOKEN: '${RENOVATE_GITHUB_COM_TOKEN}'
                RENOVATE_CONFIG_FILE: "" # /config/renovate-config.json
                LOG_LEVEL: debug
                RENOVATE_CACHE_DIR: /tmp/renovate/cache
                # ["extract", "lookup", "full"]
                RENOVATE_DRY_RUN: "full"
                RENOVATE_REPOSITORIES: xstar97/home-ops

    persistence:
      configmap-vol:
        enabled: false
        type: configmap
        objectName: config
        defaultMode: "0777"
        mountPath: /config/
        items:
          - key: renovate-config.json
            path: renovate-config.json