x-healthcheck: &healthcheck
  test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000/health"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  mcp-adguard-home:
    scale: 1
    image: ghcr.io/samik081/mcp-adguard-home:0.9.1@sha256:bef9e14a39c4e047504a8b99f234e6f61e2fce467ca738b86b682d7b31c83ffb
    container_name: mcp-adguard-home
    restart: on-failure
    expose:
      - "3000"
    healthcheck: *healthcheck
    env_file:
      - ./mcp.enc.env
networks:
  internal:
    driver: bridge
