---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: sonarr
spec:
  interval: 30m
  timeout: 25m
  maxHistory: 3
  # enabled | warn
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: sonarr
      version: 26.9.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gatus:
      group: media-managers
    global:
      stopAll: false
    credentials:
      cf-restic:
        bucket: "${CF_S3_RESTIC_BUCKET}-sonarr"
      rfs-restic:
        bucket: "${RUSTFS_S3_RESTIC_BUCKET}-sonarr"
    securityContext:
      readOnlyRootFilesystem: false
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                # SONARR__SERVER__PORT: "{{ .Values.service.main.ports.main.port }}"
                SONARR__AUTH__METHOD: External
                SONARR__AUTH__REQUIRED: DisabledForLocalAddresses
                SONARR__APP__THEME: dark

    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        annotations:
          nginx.ingress.kubernetes.io/custom-http-errors: "599"
        hosts:
          - host: series.sonarr.${DOMAIN_2}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: true
          homepage:
            enabled: true
            name: Sonarr (Series)
            group: "Media Manager"
            siteMonitor: http://sonarr.sonarr.svc.cluster.local:8989
            widget:
              custom:
                key: "${SONARR_SERIES_KEY}"
          certManager:
            enabled: true
            certificateIssuer: general-le-prod
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      media:
        enabled: true
        type: nfs
        server: ${SCALE_IP}
        path: ${MEDIA_NFS}
        mountPath: "${MEDIA_LOCAL}"
      downloads:
        enabled: true
        type: nfs
        server: ${SCALE_IP}
        path: ${DOWNLOADS_NFS}
        mountPath: "${DOWNLOADS_LOCAL}"
