apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authelia
resources:
  - helm-release.yaml
  - authelia-oidc.secret.yaml
  - authelia-configfile.configmap.yaml
components:
  - ../../../../components/ns
  - ../../../../components/notifications/discord
  - ../../../../components/gatus/service