apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: authelia
resources:
  - helm-release.yaml
  - namespace.yaml
  - authelia-oidc.secret.yaml
  # - authelia-configfile.configmap.yaml
configMapGenerator:
  - name: authelia-configfile
    namespace: authelia
    files:
      - configuration.yaml=./configuration.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: authelia
    meta.helm.sh/release-namespace: authelia
    reloader.stakater.com/match: "true"
components:
  - ../../../../components/restic
  - ../../../../components/notifications/discord
  - ../../../../components/gatus/service
