apiVersion: v1
kind: Secret
metadata:
  name: external-dns-adguard
  namespace: external-dns-adguard
type: Opaque
stringData:
  url: ENC[AES256_GCM,data:3jc+JaYegdgTN42yMhBtvA1wMFI=,iv:CbVczN44sHifn0U6cG//rt/QuOP+o7p+Olh7d2ws2As=,tag:u1ZrQ2e2cr33tukXt9shtQ==,type:str]
  user: ENC[AES256_GCM,data:CpFdq8j/Kg==,iv:4Qm8pqYK7Tpu62kXDn3hkhKybnz55kTe/U2dwxPn7DA=,tag:UB/wWBoAQ1BWhJSck9JDsw==,type:str]
  password: ENC[AES256_GCM,data:5Hbgplw9VkTkKYAxcrg=,iv:8mukTmkhBixscKYWwlWs9ZI1JhHuZpACJxLwVBT2JBw=,tag:AVnrKvwdyvOIDmaJQaK1Wg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTDVjVXMvZW84aXdXb3JC
        WDhMaXppZUlwdEhmZGh5R2lKT211ZFdRWTNnCjJiam1yV05GU2FQR2MyM01YZjM5
        SWNneXN5RlltbG91RlRTcU5rd3g5dE0KLS0tIEV2Z2QzdE43bmxiQWFvOS9xbVJ6
        bWpycWdCcDdtaFRaZlpNeTBZM0pDQ0EKReXAnlvt5LRk9pMxslHPgnWDQ85s96iL
        G/nM8bAjhPSEg7Eu/EzHnoyz8VFkrMV2D7jNepIcU04GGeNOJIbGeQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T08:21:11Z"
  mac: ENC[AES256_GCM,data:EPDavroLz/Ii7ZBXiwIttqmVNO6n6SBglq7ZoTsPqG7Cvzoq67RXWLAtXY1st+dSWNUHTyFZPE6gwS+qQYcTz0ilLnqzXwFtLnI7JEKwYauEJ3v798cxPJeEMqn1lGHvwm5NKbBLr5IiRT9D4NpMYNQ0cqre7iwkjL/f3PAlTKc=,iv:akf4V0XeeHatf5JRmcg+FkeHABfzSN7N2Fi6/Qg7TK4=,tag:B10TcuN+FiFg3jZaEmRw1A==,type:str]
  mac_only_encrypted: true
  shamir_threshold: 3
  version: 3.13.3
