apiVersion: v1
kind: Secret
metadata:
    name: external-dns-adguard
    namespace: external-dns-adguard
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:brBz24/rqn9R2kstI27dULTmHF8=,iv:vawn7l2LTO94hIW79HzyIQCU6be2xH25+ZDrOfLhQy8=,tag:K3kQBs8TeZTRUyVbb41stQ==,type:str]
    user: ENC[AES256_GCM,data:8kOtxziNYQ==,iv:rkAxoY3BGQKMNtxnrVSsCqMNzHY4Zjpwkx9wOWntZE8=,tag:aJ2QvBbDMwBrjbLD3AymEA==,type:str]
    password: ENC[AES256_GCM,data:CNCceBLtXfl82807EaU=,iv:BPOV+c3X8k9INCdYEcIvdrDOvJ2YAwdF8mKZUAuhdEM=,tag:exiTzQx3/TU90ew/nCc8dg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUzVYczRRREV2MTlFS3Bz
            YjhXR0F6S3d0VHVBb0RuT0dnL0hPZ1ZWa0JJCnJpazVjUERFK1FuUURXTzluR2Ra
            ZDM4UG9HTlJyRlFiNkRwazJhV0MyaE0KLS0tIHNDSDRLL0V5QkpyVnhTSHRWQmhn
            cG1OQkNZR3NNU1A3V0EvUUN0ODE3WGcK0CZaVwbSG+m4KuGtXQWPg9w41yNoRwE7
            TS57dX5zSwcz+P0AoM3Od/ldx7AyLOkwSqByJGjjiYkooOP6SmR/lQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tjamjeztwth5x76q52tftufdhmq97uluww3upcacps0zl04szqcqdetaan
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T07:28:13Z"
    mac: ENC[AES256_GCM,data:sF4Zq4wdrS/C1C3m+CmrqEtwXv29gbhJgWQHAvtI5jA4eWe/bEQTchNjN9uhrRljcD1i2dnhIpkDcpXzqpXYElcvMLA2s3XBcZ0SJrXrFmLnH/wYax/tceg2HgXygtdDunCaVG5Yk/0R8PrRaw40zdyBnOPIFPz5WCSVW4VQjpY=,iv:sg1uN/SEqDxppV8lEd7RAFZIbfUBRTFIHn4yW7XjZYg=,tag:G9dvw7N7EVpNsyum0Bc1+Q==,type:str]
    mac_only_encrypted: true
    shamir_threshold: 3
    version: 3.13.3
