apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - external-dns-adguard.secret.yaml
  - .decrypted~external-dns-adguard.secret.yaml
