x-healthcheckWeb: &healthcheckDb
  test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
  interval: 30s
  timeout: 30s
  retries: 3
  start_period: 30s

x-healthcheckApi: &healthcheckWeb
  test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
  interval: 30s
  timeout: 30s
  retries: 3
  start_period: 30s

services:
  scrutiny-db:
    scale: 1
    image: influxdb:2.9.1-alpine@sha256:243d7adc3edc2a3f98518e5395a9be725504acb43deb125bdcc78579b5c4bbd8
    container_name: scrutiny-db
    restart: on-failure
    healthcheck: *healthcheckDb
    expose:
      - "8086"
    networks:
      - internal
    volumes:
      - ${BASE_DOCKER_DATA_DIR}/scrutiny/db:/var/lib/influxdb2
    labels:
      wud.tag.include: ^\d+\.\d+\.\d+-alpine$
  scrutiny-web:
    scale: 1
    image: ghcr.io/analogj/scrutiny:v0.9.2-web@sha256:71be54e9960826f356fe290eb196762b2e18001e39f6ee09eeb17fe926acbf2c
    container_name: scrutiny-web
    restart: on-failure
    healthcheck: *healthcheckWeb
    ports:
      - 10080:8080
    networks:
      - network_internal
      - internal
    environment:
      SCRUTINY_WEB_INFLUXDB_HOST: 'scrutiny-db'
    volumes:
      - ${BASE_DOCKER_DATA_DIR}/scrutiny/config:/opt/scrutiny/config
    labels:
      traefik.enable: true
      traefik.http.routers.scrutiny.rule: Host(`scrutiny.${BASE_DOMAIN_0}`)
      traefik.http.services.scrutiny.loadbalancer.server.port: 10080
      traefik.http.routers.scrutiny.entrypoints: websecure
      traefik.http.routers.scrutiny.tls: true
      traefik.http.routers.scrutiny.tls.certResolver: cf
      traefik.http.routers.scrutiny.middlewares: error-pages-middleware
      wud.tag.include: ^v\d+\.\d+\.\d+-web$
  scrutiny-collector:
    scale: 1
    image: ghcr.io/analogj/scrutiny:v0.9.2-collector@sha256:a0ba60a1f3734ef82871c658a7e5545fd6b70b560935c451149ec102e35bb054
    container_name: scrutiny-collector
    restart: on-failure
    cap_add:
      - SYS_RAWIO
    networks:
      - internal
    environment:
      COLLECTOR_API_ENDPOINT: 'http://scrutiny-web:8080'
      COLLECTOR_HOST_ID: 'scrutiny-collector-seb'
      # If true forces the collector to run on startup (cron will be started after the collector completes)
      # see: https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md#collector-trigger-on-startup
      COLLECTOR_RUN_STARTUP: false
    volumes:
      - '/run/udev:/run/udev:ro'
    depends_on:
      scrutiny-web:
        condition: service_healthy
    labels:
      wud.tag.include: ^v\d+\.\d+\.\d+-collector$
    devices:
      - "/dev/sda"
networks:
  network_internal:
    external: true
  internal:
    driver: bridge
