---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apprise
  namespace: apprise
spec:
  interval: 30m
  timeout: 25m
  maxHistory: 3
  # enabled | warn
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: app-template
      version: 18.14.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gatus:
      group: networking
    global:
      stopAll: false
    credentials:
      cf-restic:
        bucket: "${CF_S3_RESTIC_BUCKET}-apprise"
      rfs-restic:
        bucket: "${RUSTFS_S3_RESTIC_BUCKET}-apprise"
    image:
      repository: caronc/apprise
      pullPolicy: IfNotPresent
      tag: v1.5.1@sha256:1871ed736799f6320d5061b72a60507f62c8747026e830175dc4b9f8adbf78dd
    service:
      main:
        ports:
          main:
            port: 8000
            
    workload:
      main:
        podSpec:
          containers:
            main:
              probes:
                liveness:
                  enabled: false
                  type: exec
                  command:
                    - sh
                    - -c
                    - 'wget'
                    - '--quiet'
                    - '--tries=1'
                    - '--spider'
                    - '{{ printf "http://%v:%v/health" (include "tc.v1.common.lib.chart.names.fullname" $) .Values.service.main.ports.main.port }}'
                readiness:
                  enabled: false
                  type: exec
                  command:
                    - sh
                    - -c
                    - 'wget'
                    - '--quiet'
                    - '--tries=1'
                    - '--spider'
                    - '{{ printf "http://%v:%v/health" (include "tc.v1.common.lib.chart.names.fullname" $) .Values.service.main.ports.main.port }}'
                # -- Startup probe configuration
                # @default -- See below
                startup:
                  # -- Enable the startup probe
                  enabled: false
                  type: exec
                  command:
                    - sh
                    - -c
                    - 'wget'
                    - '--quiet'
                    - '--tries=1'
                    - '--spider'
                    - '{{ printf "http://%v:%v/health" (include "tc.v1.common.lib.chart.names.fullname" $) .Values.service.main.ports.main.port }}'
              env:
                APPRISE_CONFIG_DIR: "{{.Values.persistence.config.mountPath }}"
                APPRISE_ATTACH_DIR: "{{.Values.persistence.attach.mountPath }}"
                APPRISE_PLUGIN_PATHS: "{{.Values.persistence.plugin.mountPath }}"
                APPRISE_WORKER_COUNT: 1
                
    ingress:
      main:
        enabled: false
        ingressClassName: "internal"
        hosts:
          - host: apprise.${DOMAIN_2}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: general-le-prod

    persistence:
      config:
        enabled: true
        mountPath: "/config"
        volsync:
          - name: config
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      attach:
        enabled: true
        mountPath: "/attach"
        volsync:
          - name: attach
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      plugin:
        enabled: true
        mountPath: "/plugin"
        volsync:
          - name: plugin
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
