---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudcmd
  namespace: cloudcmd
spec:
  interval: 30m
  timeout: 25m
  maxHistory: 3
  # enabled | warn
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: app-template
      version: 18.15.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gatus:
      group: tools
    global:
      stopAll: false
    credentials:
      cf-restic:
        bucket: "${CF_S3_RESTIC_BUCKET}-cloudcmd"
      rfs-restic:
        bucket: "${RUSTFS_S3_RESTIC_BUCKET}-cloudcmd"
    image:
      repository: ghcr.io/coderaiser/cloudcmd
      pullPolicy: IfNotPresent
      tag: 19.19.1-alpine@sha256:d5c08e5d3f0b107de165826a646a31cb00335e68804271a2f0882896da56a18c
    securityContext:
      container:
        readOnlyRootFilesystem: false
    service:
      main:
        ports:
          main:
            port: 8000
    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        hosts:
          - host: cloudcmd.${DOMAIN_2}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: general-le-prod
    persistence:
      config:
        enabled: true
        mountPath: /root
        volsync:
          - name: config
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      media:
        enabled: true
        type: nfs
        server: ${SCALE_IP}
        path: ${MEDIA_NFS}
        mountPath: ${MEDIA_LOCAL}
      downloads:
        enabled: true
        type: nfs
        server: ${SCALE_IP}
        path: ${DOWNLOADS_NFS}
        mountPath: "${DOWNLOADS_LOCAL}"
    cnpg:
      main:
        enabled: false
