---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate-config-debugger
  namespace: renovate-config-debugger
spec:
  interval: 30m
  timeout: 25m
  maxHistory: 3
  # enabled | warn
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: app-template
      version: 18.23.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gatus:
      group: core
    global:
      stopAll: false

    image:
      repository: ghcr.io/secustor/renovate-config-debugger
      pullPolicy: IfNotPresent
      tag: 0.4.0@sha256:fc15a0158b915fa3cc63dfb8551c42b9274739f48b13a26da2d77690a5e55a09

    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0

    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          main:
            enabled: true
            port: 80

    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        hosts:
          - host: debugger.renovate.${DOMAIN_2}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: general-le-prod
