---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-bluemap
  namespace: minecraft
spec:
  interval: 30m
  timeout: 25m
  maxHistory: 3
  # enabled | warn
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: app-template
      version: 18.16.6
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gatus:
      group: games-minecraft
    global:
      stopAll: false
    credentials:
      cf-restic:
        bucket: "${CF_S3_RESTIC_BUCKET}-minecraft-bluemap"
      rfs-restic:
        bucket: "${RUSTFS_S3_RESTIC_BUCKET}-minecraft-bluemap"
    image:
      repository: ghcr.io/bluemap-minecraft/bluemap
      pullPolicy: IfNotPresent
      tag: v5.23@sha256:c29b2e34edae760c90a8498aff7029540fa27a825175ae89c5899e47a0994e69

    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsGroup: 0
        runAsUser: 0

    service:
      main:
        ports:
          main:
            port: 8100
    ingress:
      main:
        enabled: true
        ingressClassName: "external"
        hosts:
          - host: maps.${DOMAIN_1}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: general-le-prod

    workload:
      main:
        podSpec:
          containers:
            main:
              args:
                - java
                - cli.jar
                - -r
                - -u
                - -w

    persistence:
      config:
        enabled: true
        targetSelector:
          main:
            main:
              mountPath: /app/config
            codeserver:
              mountPath: /app/config
        volsync:
          - name: config
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      web:
        enabled: true
        targetSelector:
          main:
            main:
              mountPath: /app/web
            codeserver:
              mountPath: /app/web
        volsync:
          - name: web
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      maps:
        enabled: true
        targetSelector:
          main:
            main:
              mountPath: /app/web/maps
            codeserver:
              mountPath: /app/web/maps
        volsync:
          - name: maps
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      data:
        enabled: true
        targetSelector:
          main:
            main:
              mountPath: /app/data
            codeserver:
              mountPath: /app/data
        volsync:
          - name: data
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      mc-java-family-data:
        enabled: true
        type: pvc    
        dataSource:
          kind: "PersistentVolumeClaim"
          name: "existingPVC"
        existingClaim: minecraft-fam-minecraft-java-data
        mountPath: /worlds/family
        readOnly: true

    addons:
      codeserver:
        enabled: true
        service:
          type: "ClusterIP"
          ports:
            codeserver:
              port: 36107
        ingress:
          enabled: true
          ingressClassName: "internal"
          hosts:
            - host: editor.maps.${DOMAIN_2}
              paths:
                - path: /
                  # Ignored if not kubeVersion >= 1.14-0
                  pathType: Prefix
          integrations:
            nginx:
              enabled: true
              auth:
                type: "authelia"
                internalHost: "authelia.authelia.svc.cluster.local:9091"
                externalHost: "auth.${DOMAIN_2}"
            certManager:
              enabled: true
              certificateIssuer: general-le-prod

    mariadb:
      enabled: true
      mariadbUsername: bluemap
      mariadbDatabase: bluemap
      backups:
        enabled: true
        credentials: cf-restic
        retentionPolicy: "7d"
        scheduledBackups:
          - name: daily-backup
            # https://crontab.guru/#10_0_*_*_*
            schedule: "10 0 * * *"
            backupOwnerReference: self
            immediate: true
            suspend: false
