---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/tuppr.home-operations.com/talosupgrade_v1alpha1.json
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
  namespace: system-upgrade
  annotations:
    tuppr.home-operations.com/factory-url: "https://factory.talos.dev/metal-installer"
    # tuppr.home-operations.com/schematic: "7927f459c7792c92502868c407ede3456e31a3e976df96799fced2d32127b002"
spec:
  talos:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/installer
    version: v1.13.6

  policy:
    debug: true          # Optional, verbose logging
    force: false         # Optional, skip etcd health checks
    rebootMode: default  # Optional, default|powercycle
    placement: soft      # Optional, hard|soft

  # Maintenance windows (optional)
  # maintenance:
  #   windows:
  #     - start: "0 2 * * 0" # Cron expression (Sunday 02:00)
  #       duration: "4h" # How long window stays open
  #       timezone: "UTC" # IANA timezone, default UTC
