---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/tuppr.home-operations.com/talosupgrade_v1alpha1.json
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
  namespace: system-upgrade
  annotations:
    tuppr.home-operations.com/factory-url: "https://factory.talos.dev/metal-installer"
    tuppr.home-operations.com/schematic: "96a7fe177deee42d93c052fff40e573ed50436693c7dfd9c2b886556514def01"
spec:
  talos:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/installer
    version: v1.13.6

  policy:
    debug: true          # Optional, verbose logging
    force: true         # Optional, skip etcd health checks
    rebootMode: powercycle  # Optional, default|powercycle
    placement: hard      # Optional, hard|soft

  # Maintenance windows (optional)
  # maintenance:
  #   windows:
  #     - start: "0 2 * * 0" # Cron expression (Sunday 02:00)
  #       duration: "4h" # How long window stays open
  #       timezone: "UTC" # IANA timezone, default UTC
