# Path of helm-release file to skip during CI testing
skipList:
  - clusters/main/kubernetes/kube-system/cilium/app
  - clusters/main/kubernetes/system/longhorn/app
  - clusters/main/kubernetes/apps/mend-renovate/app
  - clusters/main/kubernetes/auth/authelia/app
  - clusters/main/kubernetes/core/clusterissuer/app
dummyEnv:
  DOMAIN_0: dummy0.local
  DOMAIN_1: dummy1.local
  DOMAIN_2: dummy2.local
  MEDIA_NFS: /mnt/plex/media
  MEDIA_LOCAL: /media
  DOWNLOADS_NFS: /mnt/SSD/downloads
  DOWNLOADS_LOCAL: /downloads
  ROMS_NFS: /mnt/SSD/games/roms
  DOCS_NFS: /mnt/SSD/documents
  PODNET: 172.16.0.0/16
  SVCNET: 172.17.0.0/16
  METALLB_RANGE: 10.0.0.220-10.0.0.254
  NGINX_EXTERNAL_IP: 10.0.0.223
  NGINX_INTERNAL_IP: 10.0.0.224