---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  releaseName: longhorn
  timeout: 25m
  maxHistory: 3
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: longhorn
      version: 1.12.0
      sourceRef:
        kind: HelmRepository
        name: home-ops-mirror
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gatus:
      group: core
    defaultSettings:
      # Increase to 3 for a multi-node cluster
      defaultReplicaCount: "1"
      # Overprovisioning might be needed when using volsync
      storageOverProvisioningPercentage: "100000"
      # Percentage of the total allocatable CPU resources on each node to be reserved for each instance manager pod. The default value is {"v1":"12","v2":"12"}.
      guaranteedInstanceManagerCPU: 5
    persistence:
      # Set to false to pick another CSI as default
      defaultClass: true
      # Increase to 3 for a multi-node cluster
      defaultClassReplicaCount: "1"
    csi:
      attacherReplicaCount: "1"
      provisionerReplicaCount: "1"
      resizerReplicaCount: "1"
      snapshotterReplicaCount: "1"
    longhornUI:
      replicas: "1"
    metrics:
      serviceMonitor:
        enabled: true
