x-healthcheck: &healthcheck
  test: ["CMD", "/dozzle", "healthcheck"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  dozzle:
    scale: 1
    image: amir20/dozzle:v10.6.3@sha256:3d42f4c7b27f475117004f8524b52b6ea2cc1cdc39a508892d6b81ffb2883160
    container_name: dozzle
    restart: on-failure
    environment:
      DOZZLE_ADDR: :30064
      DOZZLE_ENABLE_ACTIONS: true
      DOZZLE_ENABLE_SHELL: true
      DOZZLE_NO_ANALYTICS: true
    networks:
      - network_internal
    ports:
      - 30064:30064
    healthcheck: *healthcheck
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      wud.tag.include: ^\d+\.\d+\.\d+$
networks:
  network_internal:
    external: true
  internal:
    driver: bridge
