x-healthcheck: &healthcheck
  test: ["CMD", "/dozzle", "healthcheck"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  dozzle:
    scale: 1
    image: amir20/dozzle:v11.3.0@sha256:a7d69d20891d3dcc82636e24afa4c1c162b41d0673ef798b14f09e6b69accc5a
    container_name: dozzle
    restart: on-failure
    environment:
      DOZZLE_ADDR: :30064
      DOZZLE_ENABLE_ACTIONS: true
      DOZZLE_ENABLE_SHELL: true
      DOZZLE_NO_ANALYTICS: true
    networks:
      - internal
      - network_internal
    expose:
      - "30064"
    healthcheck: *healthcheck
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.dozzle.rule: Host(`dozzle.nas.local`)
      traefik.http.routers.dozzle.entrypoints: web
      traefik.http.routers.dozzle.service: dozzle
      traefik.http.services.dozzle.loadbalancer.server.port: "30064"
      traefik.http.services.dozzle.loadbalancer.server.scheme: http
      # Register dashboard DNS record with AdGuard.
      adguard.dns: "traefik.nas.local"
networks:
  network_internal:
    external: true
  internal:
    driver: bridge
