x-healthcheck: &healthcheck
  test: ["CMD", "cloudflared", "tunnel", "--metrics", "localhost:8080", "ready"]
  interval: 30s
  timeout: 30s
  retries: 3
  start_period: 30s

services:
  cloudflared:
    scale: 1
    image: cloudflare/cloudflared:2026.7.3@sha256:e39ee8da81ad5e05d77f38d2f51c60ca51bf2a8450ac3abab50c17fdb91d91bf
    container_name: cloudflared
    restart: on-failure
    command: tunnel --no-autoupdate --metrics 127.0.0.1:8080 run --token ${CF_TUNNEL_TOKEN_0}
    networks:
      - network_internal
    expose:
      - "8080"
    healthcheck: *healthcheck
    labels:
      wud.tag.include: ^\d+\.\d+\.\d+$
      homepage.group: Networking
      homepage.name: CloudFlared
      homepage.icon: cloudflare.png
      homepage.widget.type: cloudflared
      homepage.widget.tunnelid: ${CF_TUNNEL_ID_0}
      homepage.widget.accountid: ${CF_ACCOUNT_ID_0}
      homepage.widget.key: ${CF_KEY_TOKEN_0}
networks:
  network_internal:
    external: true
  internal:
    driver: bridge
