http:
  routers:
    cups:
      rule: 'Host(`cups.{{ env "DOMAIN_0" }}`)'
      entryPoints:
        - websecure
      middlewares:
        - default-headers
      service: cups-service
      tls:
        certResolver: cf

  middlewares:
    cups-host:
      headers:
        customRequestHeaders:
          Host: '{{ env "CUPS_LOCAL_DOMAIN" }}'
          X-Forwarded-Proto: "https"

  services:
    cups-service:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: 'http://{{ env "CUPS_LOCAL_DOMAIN" }}'
