http:
  routers:
    cups:
      rule: 'Host(`cups.{{ env "DOMAIN_0" }}`)'
      middlewares:
        - default-headers
        - https-redirectscheme
      entryPoints:
        - websecure
      service: cups-service
      tls:
        certResolver: cf
  services:
    cups-service:
      loadBalancer:
        serversTransport: myInsecureTransport
        servers:
          - url: 'https://{{ env "CUPS_IP" }}:631'
        passHostHeader: true
