http:
  routers:
    ha:
      rule: 'Host(`homeassistant.{{ env "DOMAIN_0" }}`)'
      entryPoints:
        - websecure
      service: ha-service
      tls:
        certResolver: cf
  services:
    ha-service:
      loadBalancer:
        servers:
          - url: '{{ env "HA_LOCAL_DOMAIN" }}'
