http:
  routers:
    ha:
      rule: 'Host(`homeassistant.{{ env "BASE_DOMAIN_0" }}`)'
      entryPoints:
        - websecure
      service: ha-service
      tls:
        certResolver: cf
  services:
    ha-service:
      loadBalancer:
        servers:
          - url: '{{ env "HOME_ASSISTANT_HOSTNAME_LOCAL" }}'
