http:
  routers:
    router-adguard:
      rule: 'Host(`adg.{{ env "DOMAIN_0" }}`)'
      entryPoints:
        - websecure
      service: router-adguard-service
      tls:
        certResolver: cf

  services:
    router-adguard-service:
      loadBalancer:
        servers:
          - url: 'http://{{ env "ROUTER_LOCAL_DOMAIN" }}:3000'