http:
  routers:
    seb-cockpit:
      rule: 'Host(`cockpit.{{ env "DOMAIN_0" }}`)'
      entryPoints:
        - websecure
      service: seb-cockpit-service
      tls:
        certResolver: cf

  services:
    seb-cockpit-service:
      loadBalancer:
        servers:
          - url: 'http://{{ env "SEB_LOCAL_DOMAIN" }}:9090'
        serversTransport: cockpit-transport

  serversTransports:
    cockpit-transport:
      insecureSkipVerify: true