apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - cloudcmd/ks.yaml
  - dozzle/ks.yaml
  - doublecommander/ks.yaml
  - feedcord/ks.yaml
  # - fileshelter/ks.yaml
  - it-tools/ks.yaml
  - omni-tools/ks.yaml
  # - reubah/ks.yaml
  # - restreamer/ks.yaml
  # - snippet-box/ks.yaml
  # - stirling-pdf/ks.yaml
  - string-is/ks.yaml