---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tapmap
  namespace: tapmap
spec:
  interval: 30m
  timeout: 25m
  maxHistory: 3
  driftDetection:
    mode: warn
  chart:
    spec:
      chart: app-template
      version: 18.8.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gatus:
      group: observability
    global:
      stopAll: false
    credentials:
      cf-restic:
        bucket: "${CF_S3_RESTIC_BUCKET}-tapmap"
      rfs-restic:
        bucket: "${RUSTFS_S3_RESTIC_BUCKET}-tapmap"
    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        # capabilities:
        #   add:
        #     - NET_RAW
    # podOptions:
    #  hostNetwork: true
    image:
      repository: olalie/tapmap
      pullPolicy: IfNotPresent
      tag: v1.7.2@sha256:b1492e872e849e87f64aa22da85ef5ef55c89ee5297265c765c452ce54cbf3c8 
    geoImage:
      repository: ghcr.io/maxmind/geoipupdate
      pullPolicy: IfNotPresent
      tag: v7.1.1@sha256:faecdca22579730ab0b7dea5aa9af350bb3c93cb9d39845c173639ead30346d2

    service:
      main:
        type: ClusterIP
        ports:
          main:
            port: 3000
    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        hosts:
          - host: tpmtalos.${DOMAIN_2}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: true
            auth:
              type: "authelia"
              internalHost: "authelia.authelia.svc.cluster.local:9091"
              externalHost: "auth.${DOMAIN_2}"
          certManager:
            enabled: true
            certificateIssuer: general-le-prod
    workload:
      main:
        enabled: true
        primary: true
        podSpec:
          containers:
            main:
              enabled: true
              primary: true
              env:
                TAPMAP_IN_DOCKER: 1
                TAPMAP_HOST: 0.0.0.0
                TAPMAP_PORT: "{{ .Values.service.main.ports.main.port }}"
                # manual pinpoint
                # TAPMAP_LON=10.7522
                # TAPMAP_LAT=59.9139
            geoipupdate:
              enabled: true
              imageSelector: geoImage
              probes:
                liveness:
                  enabled: false
                readiness:
                  enabled: false
                startup:
                  enabled: false
              env:
                GEOIPUPDATE_DB_DIR: "{{ .Values.persistence.data.targetSelector.main.geoipupdate.mountPath }}"
                GEOIPUPDATE_ACCOUNT_ID: "${TAPMAP_GEOIPUPDATE_ACCOUNT_ID}"
                GEOIPUPDATE_LICENSE_KEY: "${TAPMAP_GEOIPUPDATE_LICENSE_KEY}"
                GEOIPUPDATE_EDITION_IDS: "GeoLite2-City GeoLite2-ASN"
                GEOIPUPDATE_FREQUENCY: 696

    persistence:
      data:
        enabled: true
        targetSelector:
          main:
            mountPath: "/data"
            geoipupdate:
              mountPath: /data
        volsync:
          - name: data
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
