---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Home-Ops:
        - abbr: XC
          href: https://github.com/xstar97/home-ops
    - code:
        - abbr: CS
          href: https://code.{{HOMEPAGE_VAR_BASE_DOMAIN_0}}/?folder=/config
    - prunemate:
        - abbr: PM
          href: https://prunemate.{{HOMEPAGE_VAR_BASE_DOMAIN_0}}/
    - dockhand:
        - abbr: DH
          href: https://dockhand.{{HOMEPAGE_VAR_BASE_DOMAIN_0}}/
    - wol:
        - abbr: WL
          href: https://wol.{{HOMEPAGE_VAR_BASE_DOMAIN_0}}/
    - headlamp:
        - abbr: HL
          href: https://headlamp.{{HOMEPAGE_VAR_BASE_DOMAIN_1}}/
    - Renovate Operator:
        - abbr: RO
          href: https://renovate.{{HOMEPAGE_VAR_BASE_DOMAIN_1}}/
    - selfh:
        - abbr: SHST
          href: https://selfh.st/apps/?sort=recent
