---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actual
  namespace: actual
spec:
  interval: 30m
  chart:
    spec:
      chart: actualserver
      version: 16.6.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 30m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gatus:
      group: financial
    global:
      stopAll: false
    credentials:
      cf-restic:
        type: s3
        url: "${CF_S3_RESTIC_URL}"
        bucket: "${CF_S3_RESTIC_BUCKET}-actual"
        accessKey: "${CF_S3_RESTIC_ID}"
        secretKey: "${CF_S3_RESTIC_KEY}"
        encrKey: "${CF_S3_RESTIC_KEY}"
    service:
      main:
        type: ClusterIP
        ports:
          main:
            port: 5006
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                ACTUAL_OPENID_DISCOVERY_URL: https://auth.${DOMAIN_2}
                ACTUAL_OPENID_CLIENT_ID: actual-budget
                ACTUAL_OPENID_CLIENT_SECRET: ${AUTHELIA_CLIENT_ACTUAL_BUDGET_SECRET}
                ACTUAL_OPENID_SERVER_HOSTNAME: https://actual.${DOMAIN_2}
                ACTUAL_OPENID_AUTH_METHOD: oauth2
    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        annotations:
          # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          nginx.ingress.kubernetes.io/custom-http-errors: "599"
        hosts:
          - host: actual.${DOMAIN_2}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: true
            auth:
              type: "authelia"
              internalHost: "authelia.authelia.svc.cluster.local:9091"
              externalHost: "auth.${DOMAIN_2}"
          certManager:
            enabled: true
            certificateIssuer: general-le-prod
    persistence:
      data:
        volsync:
          - name: data
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
