x-healthcheck: &healthcheck
  test: ["CMD", "/doco-cd", "healthcheck"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 15s

services:
  doco-cd:
    image: ghcr.io/kimdre/doco-cd:0.122@sha256:c301a4ebe864be8e73103015d20c84784e3ced9f4f65e0f28baf71e2c350bb18
    container_name: doco-cd
    restart: unless-stopped
    # depends_on:
    #   - dockerproxy
      # apprise:
      #   condition: service_healthy
    networks:
      - internal
      - network_internal
    ports:
      - "9080:9080"
      - "9120:9120"
    healthcheck: *healthcheck
    environment:
      TZ: America/New_York
      HTTP_PORT: 9080
      APPRISE_API_URL: http://apprise:8000/notify
      APPRISE_NOTIFY_URLS: http://apprise:8000/notify/doco-cd
      APPRISE_NOTIFY_LEVEL: success
      DOCKER_SWARM_FEATURES: "false"
      DEPLOY_CONFIG_BASE_DIR: ./docker/nas/
      PASS_ENV: "false"
      POLL_CONFIG: |
        - url: https://github.com/xstar97/home-ops
          reference: main
          interval: 3600
      SOPS_AGE_KEY_FILE: /run/secrets/sops_age_key
      SSH_PRIVATE_KEY_FILE: /run/secrets/ssh_private_key
      SSH_PRIVATE_KEY_PASSPHRASE: ""
      WEBHOOK_SECRET_FILE: /run/secrets/webhook_secret
      GIT_ACCESS_TOKEN_FILE: /run/secrets/git_access_token
      # DOCKER_HOST: tcp://dockerproxy:2375
    secrets:
      - ssh_private_key
      - sops_age_key
      - webhook_secret
      - git_access_token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - doco_data:/data
      # - ${SSH_KEY_FILE}:/run/secrets/ssh_private_key:ro
      # - ${AGEKEY_FILE}:/run/secrets/sops_age_key:ro
      # - ${WEBHOOK_FILE}:/run/secrets/webhook_secret:ro
      # - ${GIT_ACCESS_TOKEN_FILE}:/run/secrets/git_access_token:ro
networks:
  internal:
    driver: bridge
  network_internal:
    external: true
volumes:
  doco_data: {}
secrets:
  ssh_private_key:
    file: ${SSH_KEY_FILE}
  sops_age_key:
    file: ${AGEKEY_FILE}
  webhook_secret:
    file: ${WEBHOOK_FILE}
  git_access_token:
    file: ${GAT_FILE}